### ISSUE TITLE
Can not set font-size for $font-size-base SASS bootstrap file for RTL mode

### ISSUE THREAD

**Issue by NabiKAZ** [MohammadYounes/rtlcss#101]
When I want to override `_variables.scss` bootstrap.
I don't have any problem with set specific font family in rtl mode with this code:

`$font-family-sans-serif:      "Helvetica Neue", Helvetica, Arial, sans-serif #{'/*rtl:prepend:"Yekan", */'} !default;`

But when I want to set new font size for rtl mode, this code does not works:

`$font-size-base:              18px #{'/*rtl:40px*/'} !default;`

And give me this error when compiling:
```
[19:07:48] gulp-ruby-sass: directory

events.js:141
      throw er; // Unhandled 'error' event
      ^
 Error: error bower_components/bootstrap-sass/assets/stylesheets/bootstrap/_variables.scss (Line 53: Undefined operation: "18px /*rtl:40px*/ times 1.25".)
```

In line 53 of `bootstrap/_variables.scss ` file is this:

`$font-size-large:         ceil(($font-size-base * 1.25)) !default; // ~18px`

Do you have any suggestion?

**Comment by MohammadYounes** [comment]
You can't use this inside variables, due to ending up with invalid SCSS syntax such as:

```scss
$font-size-large: ceil((18px /*rtl:40px*/ * 1.25)) !default; // ~18px`
```

You can define different variables and then use them as directives, for example:

```scss
// vars.scss
$font-size-base-rtl: 40px !default;;
$font-size-large-rtl: ceil(($font-size-base-rtl * 1.25)) !default; 
```

Then:
```scss
// example.scss
.example{ 
  font-size: $font-size-large  #{'/*rtl:$font-size-large-rtl*/'};
}
```
Thanks.

**Comment by NabiKAZ** [comment]
But as you can see, there are many part of `scss` files of bootstrap contain `$font-size-base` and calculation on then!
I so, can not and should not to modify original source in `bower_components` path.
I can just override `_variables.scss` bootstrap but I can not change everywhere bootstrap source and the places that use this variable.

![image](https://user-images.githubusercontent.com/246721/28151714-8b5d167c-67b1-11e7-9ac7-d1b7be7f5ab1.png)

**Comment by MohammadYounes** [comment]
Yeah, This is tool works on CSS and is not based on SCSS. 

However, You don't need to change every variable. Just don't include [rtlcss directives](http://rtlcss.com/learn/usage-guide/value-directives/) in variables that are part of another variable equation. 

For example:
```scss
$font-size-base: 18px !default;
$font-size-base-rtl: 40px !default;
$font-size-large: ceil(($font-size-base * 1.25)) #{"/*rtl:" + ceil(($font-size-base-rtl * 1.25)) + "*/"} !default;
.example {
  font-size:$font-size-large;
}
```
Gives you:
```css
.example {
  font-size: 23px /*rtl:50px*/;
}
```
Or you can implement your own [rtlcss plugin](http://rtlcss.com/learn/extending-rtlcss/writing-a-plugin/) to perform CSS wide replacement.

**Comment by NabiKAZ** [comment]
Your latest suggestion is better, but also there are the problem!

1) When I use this code:
```
$font-size-base:              18px !default;
$font-size-base-rtl:          40px !default;
$font-size-large:             ceil(($font-size-base * 1.25)) #{"/*rtl:" + ceil(($font-size-base-rtl * 1.25)) + "*/"} !default;
```
The `$font-size-large` used in another formula, be like this:
```
$input-height-large:          (ceil($font-size-large * $line-height-large) + ($padding-large-vertical * 2) + 2) !default;
```
And in because I don't know about final value of `$font-size-large`, so I can not define `$font-size-large` and `$font-size-large-rtl` be like your suggestion in here.
There are a lot of codes like this throughout of bootstrap.

2) And also, some of final variables don't used in CSS directly, for example see:
```
.panel-title {
  margin-top: 0;
  margin-bottom: 0;
  font-size: ceil(($font-size-base * 1.125));
  color: inherit;
}
```
There are a lot of codes like this throughout of bootstrap.

3) As another solution maybe can modify source code of SASS and compiler, for used of values with contain comment in functions of SASS.

4) Now, it seems to me a way that may not be so good.
We can have a `_variables-ltr.scss` and a `_variables-rtl.scss` file. with contain `$font-size-base` , `$font-family-sans-serif` and another variables with self values in ltr and rtl mode.
Now, with gulp or a bash script or every scripts, Can write a code so that in firstly compile sass file with `_variables-ltr.scss` file, and second time compile with `_variables-rtl.scss` file and then used and effective RTLCSS on output file.

**Comment by MohammadYounes** [comment]
I believe having SASS ignore comments inside interpolated value is the best solution for this issue. 👍

**Comment by NabiKAZ** [comment]
@MohammadYounes 
Nop, refer to (2) in above my reply.

**Comment by MohammadYounes** [comment]
@NabiKAZ if SASS ignores the comment and writes it to the output, you have no problem with number 2 above.

**Comment by NabiKAZ** [comment]
No! But I thinks must compile the comment, see this example:
```SCSS
$font-size-base: 18px #{'/*rtl:40px*/'} !default;
.foo {
font-size: ceil(($font-size-base * 1.125));
}
```
the SASS must compile it to this for resolve:
```CSS
.foo {
font-size: 20px /*rtl:45px*/;
}
```
for real value: ceil(18 * 1.25) = 20px  
for comment value: ceil(40 * 1.25) = 45px  
  
Do you means same this?

**Comment by MohammadYounes** [comment]
No, I don't think it's a good idea to mix the logic of pre/post processors. 

The comment value is special to rtlcss. What I meant was:

```css
.foo {
   font-size: 20px /*rtl:40px*/;
}
```
However, You can do two builds - then diff the output of both LTR and RTL to know what places need directives and update accordingly.
