### ISSUE TITLE
Integrating rtlcss into angular apps

### ISSUE THREAD

**Issue by Jalalx** [MohammadYounes/rtlcss#106]
Hello guys.

I'm looking for a way to integrate `rtlcss` into angular 4 apps. Has anyone ever tried this before? Since angular does css bundling internally, Do you know any way to apply right to left styles to generated css elements?

Thanks in advance.

**Comment by sneetsher** [comment]
@MohammadYounes , This seems invalid report and could be closed as Angular already supports RTL.

**Comment by MohammadYounes** [comment]
@sneetsher Can you share a link clarifying what type of RTL support is provided by Angular ?

**Comment by Jalalx** [comment]
There is a built-in support for right to left in [Angular Material Design docs](https://material.angular.io/cdk/bidi/overview).

**Comment by MohammadYounes** [comment]
@Jalalx This is for components to get and respond to change in the application's LTR/RTL layout direction. 

The question is does Angular do automatic flipping of CSS rules ?

**Comment by Jalalx** [comment]
@MohammadYounes I think this question should be asked in [Angular issues](https://github.com/angular/angular/issues).

**Comment by sneetsher** [comment]
@MohammadYounes Excuse me, I may created a confusion here. I looked to triage the issue. As I read only what the reporter was looking for.

Angular material design does not fully support RTL. But it has robust CSS rules, that adding `dir="rtl"` will flip many components correctly, and not all.  As far as I could test its official demos https://material.angularjs.org/latest/demo/chips

I can't say  anything about this report till, I test rtlcss with angular demos.

**Comment by MohammadYounes** [comment]
@Jalalx @sneetsher For me this was a generic question, on how to integrate rtlcss with any angular app to add automated RTL support.

As for  https://material.angularjs.org - It seems they went with manual RTL support through [mixins](https://github.com/angular/material/blob/25dd787ce377bdc05f7f9be9a7c193d80f2c777e/src/core/style/mixins.scss#L121-L145).

Thanks!

**Comment by rally-clonk** [comment]
@MohammadYounes I am trying to use RTLCSS for an Angular app. This questions seemed to be exactly what I was looking for but seems that it didn't end up answering that question specifically. So I just want to see if I can integrate RTLCSS with an angular app?

**Comment by MohammadYounes** [comment]
@rally-clonk I think it can, But I can't give a definitive answer as I haven't worked with Angular-CLI. 

Since rtlcss is a postcss plugin, I suggest searching for integrating postcss with angular instead.

**Comment by m-ahmadi** [comment]
This is how I did it using the [ngx-build-plus](https://www.npmjs.com/package/ngx-build-plus) pkg.

1. add `ngx-build-plus` to your angular project.
```
ng new myapp --style=scss --routing
cd myapp
ng add ngx-build-plus
```
2. create a `webpack.partial.js` file in root of the project directory, and put the following in it:
```javascript
const rtlcss = require('rtlcss');
const autoprefixer = require('autoprefixer');

module.exports = {
  module: {
    rules: [
      {
        test: /\.s[ac]ss$/i,
        use: [
          { loader: 'postcss-loader', options: {plugins: [autoprefixer, rtlcss]} },
          'sass-loader',
        ],
      },
    ],
  },
};
```
3. install required packages: `npm i rtlcss autoprefixer -D`
4. run `ng serve --extra-webpack-config webpack.partial.js -o` 

Done. 
now all of your .scss goes through `rtlcss` and `autoprefixer`.

**Comment by renilbabu03** [comment]
@m-ahmadi : Is there any way to dynamically apply and remove the rtl css from angular . I am using ngx-translate to use translation from english to arabic and vice versa. I would like to apply the rtl behaviour only when i switch to arabic. 

Currently i am using a seperate class called arabic.scss and when user changes from english to arabic, I add a class to <body>. This class acts as parent in arabic.scss file .

If there is any better way with rtlcss then it would be helpful like changing the behaviour realtime

**Comment by m-ahmadi** [comment]
@renilbabu03 To be honest, I have not used Angular translations since angular 2, and my understanding of them is outdated, plus I haven't used `ngx-translate` either. So as of right now, I don't have any solution for this.

But with that said, one simple thing that comes to mind is that if you do not pass your `webpack.partial.js` config to the `ngx-build-plus`, then it builds your project just like normal `ng serve` does.

So if you run `ng serve --extra-webpack-config webpack.partial.js`, you're building it with `rtlcss`,
but if you run `ng serve`, you're building it without `rtlcss`.

(`ngx-build-plus` just allows you to merge your own Webpack config with Angular configs)

But I'm sure there are other possible solutions for this too. I just don't know them yet.

**Comment by mromid** [comment]
@m-ahmadi Thnak you so lot,

Can you help me how to i use A FILE in rtlcss ??
I want just bootstrap.scss use rtlcss and convert.


I try with this code but not working :(


`module.exports = {
  module: {
    rules: [
      {
        test: /bootstrap.scss$/i,
        use: [
          {
            loader: 'postcss-loader',
            options: {
              postcssOptions: {plugins: [autoprefixer, rtlcss]}
            }
          },
          'sass-loader',
        ],
      },
    ],
  },
};`

**Comment by m-ahmadi** [comment]
@mromid 

```js
> module.exports = {
>   module: {
>     rules: [
>       {
>         test: /bootstrap.scss$/i,
>         use: [
>           {
>             loader: 'postcss-loader',
>             options: {
>               postcssOptions: {plugins: [autoprefixer, rtlcss]}
>             }
>           },
>           'sass-loader',
>         ],
>       },
>     ],
>   },
> };
 ```
This config is working fine, I just tested it right now with Angular `13.0.2`.

To prove it, put `body {background: red !important}` at the end of the `bootstrap.scss` file and see the page changes to red.

To prove that RTLCSS is working put this👇 in `app.component.html`:
```html
`<p class="foo">lorep ipsum dollor sit amet</p>`
```
then put the this 👇in `bootstrap.scss` (or in `app.component.scss`)
```css
.foo {
  font-size: 3em;
  /*rtl:ignore*/
  text-align: right;
}
```
Now remove RTLCSS directive `/*rtl:ignore*/`  and put it back and see the page changes.

## More

If by "not working" you mean the RTL layout of your app has issues, then that's a **separate problem**.

As long as you do not get any errors after running `ng serve ...` then this is working exactly as expected.

Keep in mind, Bootstrap won't fully convert to RTL by just processing the `bootstrap.scss` file,

Bootstrap as of version `5.x.x` , comes with built-in RTL support and you don't have to do this manually. [Look here](https://getbootstrap.com/docs/5.0/getting-started/rtl/)

If you have to use Bootstrap version `4.x.x`, take a look at [this package](https://www.npmjs.com/package/bootstrap-v4-rtl)

**Comment by hafsamubarak** [comment]
> 2\. directory
hi, I converted my website to rtl successfully but I have some problems with the layout and I want to fix it making a separate SCSS file or just merging the rtl styles with the rtl styles, how can I do that?!

**Comment by catalinadorneanu** [comment]
@m-ahmadi I tried your method but it redirects me to a different localhost than the one that I'm using. How can I avoid that?

**Comment by nofalx** [comment]
With Angular moving to new build system. Using ngx-build-plus won't be the best solution. 

I added an Angular feature request to solve this issue, but it needs votes of the community

https://github.com/angular/angular-cli/issues/26867
