### ISSUE TITLE
issue with background-position

### ISSUE THREAD

**Issue by vahid-sanati** [MohammadYounes/rtlcss#107]
Using `background-position` when first Y value then X value comes, the value doesn't transform.

example:
`background-position: top right;
`

transformed:
`background-position: top right;
`

tested using online tool in rtlcss.com

**Comment by MohammadYounes** [comment]
Thanks for reporting this, It is valid in case of keywords only position. 

Nevertheless, it's a good practice to state position in the form of `X Y` as  `background-position: 0 right;` is considered invalid.

Will fix soon!

**Comment by MohammadYounes** [comment]
@vahid-sanati Fixed in v2.2.1
