### ISSUE TITLE
background-position (0 to 100%)

### ISSUE THREAD

**Issue by VxMxPx** [MohammadYounes/rtlcss#109]
Behavior:

`background-position: 0 20px;` = output => `background-position: 100% 20px;`

Expected:

`background-position: 0 20px;` = output => `background-position: 0 20px;`

This break Flags in Semantic UI (which are implemented as an image spite).

**Comment by MohammadYounes** [comment]
The current behavior is to flip the horizontal background position.  For image sprites, you should [ignore](http://rtlcss.com/learn/usage-guide/value-directives/#ignore) or [replace](http://rtlcss.com/learn/usage-guide/value-directives/#replace) the image.

Opening a PR at Semantic UI to ignore flipping the Flags rules is highly appreciated.

Thanks!

**Comment by aleen42** [comment]
@MohammadYounes `0` should be considered as `0px` and should not be calculated automatically by default unless we enable `useCalc`.
