### ISSUE TITLE
Dont compile sth

### ISSUE THREAD

**Issue by ismailbayram** [MohammadYounes/rtlcss#112]
Hello, i read the docs many times. I want to not compile to rtl some block. I tried somethings but it excluded the blocked code in rtl.

**Comment by MohammadYounes** [comment]
Hello, 

Are you sure you are using this package ? If Yes, Then you should be using [`ignore` control directive](http://rtlcss.com/learn/usage-guide/control-directives/#ignore), try the examples in the [playground](http://rtlcss.com/playground/) and see for yourself.

Thanks.
