### ISSUE TITLE
Source map

### ISSUE THREAD

**Issue by nicolashemonic** [MohammadYounes/rtlcss#117]
Hi,

Thanks for this excellent library :)

I try to add source map to output rtl css without success:
`rtlcss.configure({ map: true }).process(src);`
or
`rtlcss.process(src, { map: true });`

Instead, using postcss it works well:
`postcss().use(rtlcss()).process(src, { map: true });`

I would like to use rtlcss without postcss, it is a bug or a wrong implementation ?

Thanks !

**Comment by MohammadYounes** [comment]
Hi,

`rtlcss.process` is a shortcut to get the output CSS as a string directly without interacting with postcss API.

However, `rtlcss.configure`  returns a postcss instance, so you can do: 

```js
rtlcss.configure().process(css, { map: true } );
```

Thanks!

**Comment by nicolashemonic** [comment]
Perfect it works !

Thanks
