### ISSUE TITLE
bootstrap cdn update to 4.1 

### ISSUE THREAD

**Issue by Enalmada** [MohammadYounes/rtlcss#118]
Thanks for this amazing project.

**Comment by yabasha** [comment]
Please update it to the latest batch version of bootstrap: v.4.1.1

**Comment by m5o** [comment]
`v4.1.2` is out and hot https://blog.getbootstrap.com/2018/07/12/bootstrap-4-1-2/

**Comment by MohammadYounes** [comment]
Just published both [v4.1.3](https://rtlcss.com/cdn/css-frameworks/bootstrap/#version-4-1-3-bootstrap-rtlcss-com-docs-4-1) and [v4.2.1](https://rtlcss.com/cdn/css-frameworks/bootstrap/#version-4-2-1-bootstrap-rtlcss-com)
