### ISSUE TITLE
box-shadow

### ISSUE THREAD

**Issue by smkoBa** [MohammadYounes/rtlcss#119]
Thanks for this amazing project.
box-shadow does not work

**Comment by MohammadYounes** [comment]
Can you provide an example ?

**Comment by smkoBa** [comment]
for example in ltr style is:
 ```
body {
    border: 1px solid;
    padding: 10px;
    box-shadow: 5px 10px;
}
```

and in rtl it must be:

 ```
body {
    border: 1px solid;
    padding: 10px;
    box-shadow: -5px 10px;
}
```

**Comment by MohammadYounes** [comment]
@smkoBa  I see the expected result: https://runkit.com/embed/yi99o6diksvh
