### ISSUE TITLE
any options to get only changed properties?

### ISSUE THREAD

**Issue by yonimoses** [MohammadYounes/rtlcss#124]
so given a LTR class 

`
.test {
  direction: ltr;
  margin: 0;
  padding: 1em 2em .5em 1em;
  background-color: #353639;
  font-family: "Droid Sans", sans-serif;
  font-size: 16px;
}
`
After convert it becomes 
`
.test {
  direction: rtl;
  margin: 0;
  padding: 1em 1em .5em 2em;
  background-color: #353639;
  font-family: "Droid Sans", sans-serif;
  font-size: 16px;
}
`

It there an option to get only the changed attributes? e.g

`.test {
  direction: rtl;
}`

that way I can dynamically append smaller style sheets.

Cheers

**Comment by MohammadYounes** [comment]
No, As this tool is intended to provide complete automation. I recommend [creating a complete RTL version](https://github.com/MohammadYounes/rtlcss/wiki/Why-make-a-complete-RTL-version-%3F)

> Duplicate #13, #26, #30, #34 and #59

**Comment by yonimoses** [comment]
Good explanation!
That being said, my css is pretty big (unzipped and unminified is about ~500Kb) and adding it at runtime affects user experience .. I think I'd rather fix RTL issues here and there (like you articles states) is better approach for me then to load these huge files..

thanks
