### ISSUE TITLE
RTL Multiple CSS Files ?!

### ISSUE THREAD

**Issue by Mu9tafa-Online** [MohammadYounes/rtlcss#127]
is there any way to **RTL Multiple CSS** files at once ??

**I have 22 CSS Files that need to be RTLed .**

**Comment by MohammadYounes** [comment]
@Mu9tafa-Online Yes, you can use task runners such [grunt](https://github.com/MohammadYounes/grunt-rtlcss)/[gulp](https://github.com/jjlharrison/gulp-rtlcss) or make use of the [CLI`directory`](https://rtlcss.com/learn/usage-guide/cli/#directory) option.
