### ISSUE TITLE
Bootstrap 4 - SCSS?

### ISSUE THREAD

**Issue by typistX** [MohammadYounes/rtlcss#128]
First off thanks for your work. I see a compiled css when I download RTLCSS bootstrap, but it seems like the SCSS files are LTR?

**Comment by MohammadYounes** [comment]
@typistX Yes, the conversion is done during [build](https://github.com/RTLCSS/bootstrap/blob/v4-rtl/package.json#L32-L36) using [rtlcss](http://rtlcss.com).

**Comment by typistX** [comment]
@MohammadYounes - thanks for the quick reply. So I can’t use SCSS with it? (with Django and Django-compress)

**Comment by MohammadYounes** [comment]
@typistX The included SCSS is LTR. 

I am not familiar with Django, If you can run  [rtlcss](http://rtlcss.com) on the output CSS; you'll get the RTL version.
