### ISSUE TITLE
Can you create rtl js ?

### ISSUE THREAD

**Issue by djary** [MohammadYounes/rtlcss#129]
The big trouble that occurs during right-to-left is the inconsistency between the CSS and the javascript plugins.It disrupts the JS plugin's performance

**Comment by MohammadYounes** [comment]
@djary Do you mean converting inline CSS in the browser ? Can you elaborate more ?

**Comment by djary** [comment]
Some (most) of the "jQuery" plugins do not work properly when the "Css" is RTL, such as the slider plugin.

**Comment by MohammadYounes** [comment]
Since it's a combination of both CSS and JS, This is something that needs to be handled by the plugin author.
