### ISSUE TITLE
Is there a way to omit unchanged css rule in the output file?

### ISSUE THREAD

**Issue by tarekdj** [MohammadYounes/rtlcss#13]
I've noticed that unchanged rules (eg. ignored rules) are written to the output file. Is there a way to avoid this duplication?

**style.css:**

```
body{ 
font-family:"Droid Sans", "Helvetica Neue", Arial/*rtl:prepend:"Droid Arabic Kufi", */; 
font-size:16px/*rtl:14px*/;
}
/*rtl:ignore*/
.ignored{ 
font-size:16px;
color:red;
}
```

**style.rtl.css:**

```
body{ 
font-family:"Droid Arabic Kufi", "Droid Sans", "Helvetica Neue", Arial; 
font-size:14px;
}
.ignored{ 
font-size:16px;
color:red;
}
```

**Expected style.rtl.css:**

```
body{ 
font-family:"Droid Arabic Kufi", "Droid Sans", "Helvetica Neue", Arial; 
font-size:14px;
}
```

**Comment by NabiKAZ** [comment]
@MohammadYounes 

I think this feature can be useful if removing properties that are identical in both RTL and LTR states.
This has been seen in more WordPress templates.
In this method, on the LTR page, only the `ltr` file is added to the page, and on the RTL page, both `ltr` and `rtl` files are added to the page. Then `ltr` file properties overwrite by `rtl` file.

For example this:
```
p {
    float: left;
    margin: 20px;
    padding-left: 10px;
    color: #fff;
}
```
Convert to this:
```
p {
    float: right;
    padding-right: 10px;
}
```
Sample project: https://rtl.daskhat.ir/

**I know about the problems of this method. But as an option, it may be useful for some people and some projects.**

**Comment by MohammadYounes** [comment]
@NabiKAZ Thanks, I already responded to a similar request [here](https://github.com/MohammadYounes/rtlcss/issues/78#issuecomment-284492078).
