### ISSUE TITLE
Can RTLCSS provide an option to diff both compiled and uncompiled CSS files?

### ISSUE THREAD

**Issue by HuKaihe** [MohammadYounes/rtlcss#132]
`
.test { height: 120px; margin-left: 10px }
`
RTLCSS can read the css above and make it into the CSS below: 

`
.test { height: 120px; margin-right: 10px}
`

That's perfect!  But can it provide an option to diff these two files and provide CSS like below:

`
/*height is not changed so it is removed*/
.test { margin-right: 10px}
`
Best wishes， Look forward to your reply

**Comment by MohammadYounes** [comment]
@HuKaihe No, As this tool is intended to provide complete automation. I recommend [creating a complete RTL version](https://github.com/MohammadYounes/rtlcss/wiki/Why-make-a-complete-RTL-version-%3F)

However, I believe writing a postcss plugin to diff the two versions is a viable option.

> Duplicate #13, #26, #30, #34, #59 and #124
