### ISSUE TITLE
Asslam Alykom, i have this messege with odoo 12 /You need https://rtlcss.com/ to convert css file to right to left compatiblity.

### ISSUE THREAD

**Issue by abdelhakim-85** [MohammadYounes/rtlcss#133]

**Comment by MohammadYounes** [comment]
Wa Alaikum Assalaam, Is there a specific question here ?

**Comment by abdelhakim-85** [comment]
i get this warning message in the eclipse log . i have installed rtlcss : rtlcss version: 2.4.0 in mac osx but it is not woking .

**Comment by MohammadYounes** [comment]
Did you install it globally  `npm i -g rtlcss` ?

**Comment by abdelhakim-85** [comment]
yes : /usr/local/bin/rtlcss -> /usr/local/lib/node_modules/rtlcss/bin/rtlcss.js
+ rtlcss@2.4.0inimi
updated 1 package in 6.244s

**Comment by MohammadYounes** [comment]
I don't know, It is better to check with odoo. Open your issue [here](https://github.com/odoo/odoo/issues/new).

**Comment by MohammadYounes** [comment]
@abdelhakim-85 Did you check with odoo? Is the issue resolved ?
