### ISSUE TITLE
modal header is left aligned

### ISSUE THREAD

**Issue by coda-apps** [MohammadYounes/rtlcss#135]
Hi

Found a small issue - the h3 of the modal header is still left aligned - where it should be right aligned.

pls see sample here: https://jsfiddle.net/kneidels/aq9Laaew/303853/

any idea what needs to be fixed?

Thanks

**Comment by MohammadYounes** [comment]
Hi,

You are missing "rtl" document direction, updated sample https://jsfiddle.net/vr2gf9u8/

Thanks.

**Comment by MohammadYounes** [comment]
The recommendation is to add `dir="rtl"` to the html tag. See: 
* https://www.w3.org/International/questions/qa-html-dir
* https://www.w3.org/International/questions/qa-bidi-css-markup 

There is no need to do it via JS, I did so because I have no access to the HTML tag ... That's all.

**Comment by coda-apps** [comment]
Got it - thanks!
