### ISSUE TITLE
rtlcss: invalid config file.  TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by eragroup** [MohammadYounes/rtlcss#136]
sudo npm install -g rtlcss

CLI: rtlcss, gives this message
`rtlcss: invalid config file.  TypeError: Path must be a string. Received undefined`

**Comment by MohammadYounes** [comment]
[Configuration](https://rtlcss.com/learn/usage-guide/cli/#config) can be set using one of the following methods:
* Specify the configuration file manually via the --config flag.
* Put your config into your projects package.json file under the rtlcssConfig property.
* Use a special file .rtlcssrc or .rtlcssrc.json.

Can you provide me with the following:

1. node/npm version
2. the command used to produce this error.

Thanks.

**Comment by MohammadYounes** [comment]
@eragroup I am not familiar with odoo.

 Did you mange to resolve this ?

**Comment by eragroup** [comment]
> @eragroup I am not familiar with odoo.
> 
> Did you mange to resolve this ?

Yes, I had to re-install odoo from the official website to get it solved. The issue was because I used a third party script before for installation.
Thank you for your help.

**Comment by MohammadYounes** [comment]
@eragroup Great, Thanks for the feedback!
