### ISSUE TITLE
ignore css of an node module

### ISSUE THREAD

**Issue by hamid07ss** [MohammadYounes/rtlcss#137]
Hi.

I using leaflet and when I switch to RTL, leaflet not working anymore
because of the direction

so I want to ignore CSS of this module that I imported manually in my less file:
```
/*rtl:begin:ignore*/
@import "~leaflet/dist/leaflet.css";
/*rtl:end:ignore*/
```

but this ignore comment not working!

**Comment by MohammadYounes** [comment]
@hamid07ss It could be the comments were omitted by the minifier ? Did you try using important/special comment syntax `/*!rtl:begin:ignore*/` and `/*!rtl:end:ignore*/` ?

Also you are importing a CSS file, does the final file contain the contents of "leaflet.css" or an import statement ?

**Comment by hamid07ss** [comment]
`Also you are importing a CSS file, does the final file contain the contents of "leaflet.css" or an import statement ?`

the final file contains the contents of "leaflet.css"


and I use webpack with webpack-rtl-plugin
`/*rtl:begin:ignore*/` and `/*!rtl:end:ignore*/` working for my own css but for imported modules css not working

**Comment by MohammadYounes** [comment]
@hamid07ss Are you using `/*!...*/` or `/*...*/` ? note the `!` at the beginning of the comment.

**Comment by hamid07ss** [comment]
I test two way:
```
/*rtl:begin:ignore*/
@import "~leaflet/dist/leaflet.css";

.hamid {
  direction: ltr;
}
/*rtl:end:ignore*/
```
and
```
/*!rtl:begin:ignore*/
@import "~leaflet/dist/leaflet.css";

.hamid {
  direction: ltr;
}
/*!rtl:end:ignore*/
```

working correctly for
```
.hamid {
  direction: ltr;
}
```
and this css ignored on rtlcss
but `@import "~leaflet/dist/leaflet.css";`  not ignore

sorry about my bad English!!

**Comment by MohammadYounes** [comment]
@hamid07ss Is it possible to create a mini project showcasing the issue and share it with me ?

**Comment by MohammadYounes** [comment]
Closing due to lack of a sample project to validate against.
