### ISSUE TITLE
Support logical directions in CSS

### ISSUE THREAD

**Issue by yaroslavrudiak** [MohammadYounes/rtlcss#138]
Hey guys, thanks for doing the great feature. I'd like to ask you about the future of your plugin. Are you planing to support logical properties in CSS? Would be great to have it in next releases.

Thanks, Slavko

**Comment by MohammadYounes** [comment]
Hey @yaroslavrudiak, At the moment, there are no plans to support logical properties. However, There are multiple postcss plugins addressing this subject (*ordered by date of first commit*):

- https://github.com/bmds/postcss-logical-props/
- https://github.com/ahmadalfy/postcss-logical-properties
- https://github.com/jonathantneal/postcss-logical

Thanks!
