### ISSUE TITLE
float doesn't work 

### ISSUE THREAD

**Issue by balkees93** [MohammadYounes/rtlcss#141]
(float) doesn't work

**Comment by MohammadYounes** [comment]
How?

**Comment by balkees93** [comment]
float:right;
still right not left

**Comment by MohammadYounes** [comment]
Help me out here, I need more than right not left ?

**Comment by MohammadYounes** [comment]
Does it work here https://rtlcss.com/playground/ ?

**Comment by balkees93** [comment]
yeah it works their
when i wrote float:right/*!rtl: right*/;
or floar:right /*!rtl:ignore*/;
it still read it to right

**Comment by MohammadYounes** [comment]
When you use `float:right/*!rtl: right*/;` or ` float:right/*!rtl:ignore*/;` you are instructing rtlcss to keep the value `right`.
