### ISSUE TITLE
How does it work

### ISSUE THREAD

**Issue by ShadOoW** [MohammadYounes/rtlcss#144]
Hello,

Initially I was thinking that there is a list of revers-able css properties, but after looking at the source code, it looks like you are searching for right/left string and reversing them.

- Is this correct?
- Do you also reverse top and bottom?
- Does this support animations?

**Comment by MohammadYounes** [comment]
Hello,

> - Is this correct?

In some cases Yes, In others **No**. The complete list of processed properties can be found [here](https://rtlcss.com/learn/getting-started/why-rtlcss/#css-level-3).

> - Do you also reverse top and bottom?

No, top and bottom are the same for both LTR and RTL languages.

> - Does this support animations?

Yes, in the sense of reversing animation properties, not the animation direction.


Thanks.
