### ISSUE TITLE
Support CSS Modules Naming Convention

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [MohammadYounes/rtlcss#145]
Hi,

Thank you for this amazing framework!

I raised an [issue at Create React App](https://github.com/facebook/create-react-app/issues/7567#issuecomment-523079187) and they told that I must raise it here.

I have a lot of CSS modules and their names look like this one `LoginForm.module.css` when I run `rtlcss -d myDir --ext ".rtl.module.css"` their names become `LoginForm.module.rtl.module.css` I want it to be `LoginForm.rtl.module.css`

All the best,
Mohammed

**Comment by MohammadYounes** [comment]
Hi,

Current version considers the part after the last dot to be the extension, which is the most common case. 

What you can do is to specify a temp output folder, then run another script to copy the files from the temp folder to the desired destination with the names you want.

Thanks!
