### ISSUE TITLE
Require not defined

### ISSUE THREAD

**Issue by mahdiG** [MohammadYounes/rtlcss#146]
Hello. I installed rtlcss in my lit-element project run with polymer-cli and when I use rtlcss I get an error saying require is not defined. I checked your package in node_modules and you've used require to import some libraries and require is not defined by default in js.
Can you use es6 imports instead of require? Or if you can't, can you include require-js or something like that in your package.json so it gets installed when installing rtlcss? thanks.

**Comment by MohammadYounes** [comment]
This a node library, If you want to use it in the browser, you can use Browserify.
 See https://stackoverflow.com/questions/27617143/cant-covert-css-to-rtl-using-javascript-library

**Comment by mahdiG** [comment]
Interesting. Are you planning on making it so that we can convert the direction on the fly on browser? For example you click a button and everything is converted from ltr to rtl or vice versa.
