### ISSUE TITLE
can u add Diffchecker to the online editor ?

### ISSUE THREAD

**Issue by djary** [MohammadYounes/rtlcss#147]
hi , this is a great site for RTL languages . can u add Diffchecker (Compare two CSS files, LTR and RTL Versions) to Online editor ?

**Comment by MohammadYounes** [comment]
Hi, It already exists :)

![image](https://user-images.githubusercontent.com/4712046/66711560-38cc3200-ed9f-11e9-96d0-7b339fed26e0.png)

![image](https://user-images.githubusercontent.com/4712046/66711561-4386c700-ed9f-11e9-8c5c-9431474ed041.png)
