### ISSUE TITLE
OPTION: enable auto rename only when a pair exist

### ISSUE THREAD

**Issue by LyoNick** [MohammadYounes/rtlcss#15]
i.e:
while the example with *i.icon.angle.left:before* and *i.icon.angle.right:before* show it potential,
this can get out of hand fast, consider the following:

```html
<div class="left-item"">...</div>
```
```css
.left-item { background-color: blue;}
```
but **without** a matching *right-item* class in the markup.

auto rename will replace the class in the css, leaving the markup pointing nowhere.

and since unfortunately this is frequent, i would like an option for auto rename to not only limit replacing when there is a directional content, but also (or even instead) when he can NOT find a mirror selector.

i know this is a big feature, but without that ... auto rename will be mostly disabled.

other option is allowing to run auto rename **on its own**?
this way, one can turn it off, run trough RTLCSS,
than run the rtl-ed results through auto rename,
making the diff to inspect such cases in the markup a lot smaller.
(this will work when one have control over the markup)

**Comment by LyoNick** [comment]
thanks for that!

**Comment by MohammadYounes** [comment]
You are welcome :)
