### ISSUE TITLE
Reset RTL CSS Converted Properties & Remove Class unchanged Properties

### ISSUE THREAD

**Issue by soheilkheiri** [MohammadYounes/rtlcss#151]
hi we need  Reset RTL CSS Converted Properties and Remove Class unchanged Properties

**for example :**
`.example-class {
  left: 5px;
  margin-left: 8px;
}
`

**Reset RTL CSS Converted Properties :**
`.example-class {
    right: 5px;
    left: auto;
    margin-right: 8px;
    margin-left: auto;
}
`

Some features are needed Reset to overwrite the previous value if the second part is loaded for overwrite.

**Delete not change Class Properties:**
`.example-A { width: 100%; margin-bottom: 10px !important; }`
`.example-B { width: 100%; text-align:left;}`

**after active : "Remove Class unchanged Properties"**
`
.example-B { text-align:right;}
`

**Comment by MohammadYounes** [comment]
@soheilkheiri This tool is intended to provide complete automation. I recommend [creating a complete RTL version](https://github.com/MohammadYounes/rtlcss/wiki/Why-make-a-complete-RTL-version-%3F)

> Duplicate #13, #26, #30, #34, #59, #124 and #132

**Comment by soheilkheiri** [comment]
I read the link but couldn't figure out how to use it.

How to use in online website : https://rtlcss.com/playground/

comment ? or option ?

**Comment by MohammadYounes** [comment]
@soheilkheiri This tool does only generate a complete version of the input CSS with directional declarations flipped, there is no option to do what you requested.

**Comment by soheilkheiri** [comment]
So don't you add these options to the online version?
