### ISSUE TITLE
a problem from class row

### ISSUE THREAD

**Issue by alirezaseif28** [MohammadYounes/rtlcss#158]
a definition class row
sort by left to right

**Comment by MohammadYounes** [comment]
Closing for lack of clarity, Feel free to reopen if you can provide a more clear description of your issue.

**Comment by alirezaseif28** [comment]
hi .
a definition 
`<div class="row">alireza</div>`
.display left to right.

**Comment by MohammadYounes** [comment]
@alirezaseif28 If you are referring to bootstrap `row`, then you need to set the document direction as it uses `flexbox`.
