### ISSUE TITLE
Ignore value directive with grunt-rtlcss is not working

### ISSUE THREAD

**Issue by sriram275** [MohammadYounes/rtlcss#166]
Hi,
Currently using the following version of grunt-rtlcss 
"grunt-rtlcss": "2.0.2",

and tryining to use ignore value directive like below 
`direction: ltr #{"/*rtl:ignore*/"};`
is not working means in the output file it is converting the direction like below
`direction: rtl /*rtl:ignore*/`

Is there way to achieve this?

**Comment by MohammadYounes** [comment]
This is a known postcss [issue](https://github.com/postcss/postcss/issues/1110), If a declaration value ends with a comment, postcss parses the comment into raw value except when that declaration has no semicolon, it's parsed into a separate comment node.

To work around this, place the comment above the declaration:
```css
.cls {
  /*rtl:ignore*/
  direction: ltr;
}
```
