### ISSUE TITLE
Bootstrap CDN: backward swipe on carousel component

### ISSUE THREAD

**Issue by geminorum** [MohammadYounes/rtlcss#168]
Using [RTL Bootstrap](https://rtlcss.com/cdn/css-frameworks/bootstrap/) v4.2.1 from your CDN, the carousel swipe event on touch screens is working back-wards. 

[example](https://codepen.io/geminorum/full/MWKadXP)

**Comment by MohammadYounes** [comment]
Thanks for reporting this. Due to limited availability, it might take me a while to fix/publish this... PRs are welcome!

**Comment by MohammadYounes** [comment]
@geminorum fixed in v4.5.3
