### ISSUE TITLE
findup - no longer maintained 

### ISSUE THREAD

**Issue by sunandhachettiannan** [MohammadYounes/rtlcss#173]
@MohammadYounes 
Can we use alternative lib for **findup** because the one in use is no longer maintained.
findup needs to update the colors lib version because colors@~0.6.0-1 doesn't have the valid license  and it's updated with 1.4.0 version - https://github.com/Marak/colors.js/commit/5152d16f22789d66e107275e006f88517641ed18

**Comment by MohammadYounes** [comment]
Most dependencies require update. Due to limited availability it might take a while to do this ... PRs are welcome!

**Comment by LKummer** [comment]
Hello @MohammadYounes, I like your project and would like to contribute.

[find-up](https://www.npmjs.com/package/find-up) looks like a good option.

* Almost a drop-in replacement.
* Very popular, used by Mocha and Yeoman.
* Actively maintained.

Only issue I see is that it requires Node 10 while the CI runs Node 4, 5 and 6. I am interested in helping with that as well, and will open a new issue shortly.

Is this library choice fine?
