### ISSUE TITLE
Update CI to Run Current Node Versions

### ISSUE THREAD

**Issue by LKummer** [MohammadYounes/rtlcss#174]
Hello @MohammadYounes. This is a follow up to my comment in #173.

The current Travis based CI runs outdated versions of Node. It blocks dependency updates and the library change mentioned in #173.

I believe the CI should run Node 10 (maintenance LTS), Node 12 (active LTS) and Node 14 (current).
As the project handles paths for configuration loading, it might also be beneficial to run the CI on Windows as well as Ubuntu. Would you like Mac jobs as well?

I would also like to switch to Github Actions for a few reasons:

* I had very good experience with it both in my own projects and when contributing.
* Easier to test on my end before submitting the PR.
* Nicely integrated with Github, showing individual runs on PR.
* More generous open source plan allowing more concurrent runs.

The changes I am suggesting boil down to:

* Refactor the CI to Github Actions.
* Run on Node 10, 12 and 14.
* Run on Ubuntu, Windows and Mac.

I would like to contribute these changes. Once you give the green light to switch to Github Actions you can expect a PR very soon.

Does everything sound good to you?

**Comment by XhmikosR** [comment]
@MohammadYounes I believe this can be closed now after #186
