### ISSUE TITLE
Last value directive is ignored in Sass compressed mode

### ISSUE THREAD

**Issue by anoukinsyde** [MohammadYounes/rtlcss#176]
The last value directive in a list is ignored when Sass is set to compressed mode. This is because the compressed mode will automatically **remove the trailing semicolon**. The value directive is ignored if it isn't followed by a trailing semicolon. This is currently causing issues for me.

These work: 
`.element {
  transform: none #{'/*!rtl:scaleX(-1) */'};
}
`

`.element { transform: none #{'/*!rtl:scaleX(-1) */'}; z-index:1 }`

But this doesn't work (sass compressed):
`.element { transform: none #{'/*!rtl:scaleX(-1) */'} }`

Hope someone can look into this. Thanks in advance.

**Comment by MohammadYounes** [comment]
This is an old issue related to postcss see (https://github.com/postcss/postcss/issues/1110). I'll keep it open to try and handle it from rtlcss side once I find the time!

**Comment by MohammadYounes** [comment]
With ee9dc53237e73b725f800a9a7a392cfc53f67e4a you can place the comment anywhere inside the decl. value. for example:

```scss
.element { transform: #{'/*!rtl:scaleX(-1) */'} none }
```
