### ISSUE TITLE
Bootstrap RTL

### ISSUE THREAD

**Issue by sajadafaghiy** [MohammadYounes/rtlcss#178]
Can you explain how rtl css files of bootstrap at [here](http://bootstrap.rtlcss.com/) are generated?
If they're generated with CLI without any other changes please say that are you using default config for that or not?
These files behave differently from the files generated in mine!

**Comment by MohammadYounes** [comment]
I have updated the build process ([410e4790](https://github.com/RTLCSS/bootstrap/commit/410e4790bd8446015e7bcf3b9ad7c18d591fdd66)), See https://github.com/RTLCSS/bootstrap repo.
