### ISSUE TITLE
CLI: Support for Min and Source Map files

### ISSUE THREAD

**Issue by 96fauj** [MohammadYounes/rtlcss#179]
How do you have RTLCSS generate the SourceMap files when generating the RTL files?

- Source map 
My config is as follows - I can't relate to the Api and the documents on postcss as to how I can put it in this config?

So I've put that I want maps, great but this will do it inline.

- Minify
Setting minify to true seems to do nothing for me, the output is still pretty. What I ideally want to achieve through the cli is

1. Input .CSS file 
2. Output the following
- .min.css
- .css.map
- .rtl.css 
- .rtl.css.map
- .rtl.min.css

```
{
    "options": {
        "preserveComments": false,
        "preserveDirectives": false,
        "swapLeftRightInUrl": false,
        "swapLtrRtlInUrl": false,
        "swapWestEastInUrl": false,
        "autoRename": false,
        "greedy": false,
        "enableLogging": false,
        "minify": true
    },
    "rules": [ ],
    "declarations": [ ],
    "properties": [ ],
    "map": true
}
```

**Comment by MohammadYounes** [comment]
@96fauj These are the setting for the rtlcss v1, this has changed in v2 which no longer has the minify option.

Source maps generation is handled entirely by postcss. You set such config on postcss and use rtlcss as a plugin.

```js

var result = postcss().use(rtlcss([options , plugins, hooks]))
                      .process(css[, postcssOptions]);

```

For `postcssOptions` see [postcss docs](https://postcss.org/api/#processoptions).
