### ISSUE TITLE
Feature Request: ability to save output log per file in a configurable dir

### ISSUE THREAD

**Issue by LyoNick** [MohammadYounes/rtlcss#18]
I would like the ability to specify a log folder so when using ``` rtlcss -d source-folder dest-folder ``` 
it will save the rtlcss logs per file like the sourcemap
and also to be able to set it in the config file.

so for example:
```
ltr-dir1/file1.css
ltr-dir2//file1.css
```
will output an *optional* additional:
```
log-dir1/file1.log
log-dir2//file1.log
```

**Comment by MohammadYounes** [comment]
Why not to use command redirection operators ?

 `rtlcss -d source-folder dest-folder > output\logs.txt`

**Comment by LyoNick** [comment]
i could, but this will aggregate all the changes into a single file.

although, unless implementing it is *very* trivial, it might be out of scope for this project.
since  i can process the file one by one with the redirection operator, perhaps even use gulp | grunt,
it is not an important feature, more like a nice to have.

**Comment by MohammadYounes** [comment]
Yes, I think this should be kept external and not added as a feature. 

Thanks.
