### ISSUE TITLE
Postcss 8

### ISSUE THREAD

**Issue by mjhenkes** [MohammadYounes/rtlcss#182]
This project currently depends on [Postcss 6](https://github.com/MohammadYounes/rtlcss/blob/master/package.json#L32) any plans to upgrade to Postcss 8?

Migration guide: https://evilmartians.com/chronicles/postcss-8-plugin-migration.

**Comment by MohammadYounes** [comment]
Closed in cd0e5cd3b362a6fd883664576a011f2c0a65dbb5

**Comment by mjhenkes** [comment]
Thanks @MohammadYounes! 🎉  ❤️
