### ISSUE TITLE
Feature Request: configurable file renaming scheme

### ISSUE THREAD

**Issue by LyoNick** [MohammadYounes/rtlcss#19]
configurable file renaming scheme for the rtl will be useful
(i.e some projects require ``` file-rtl.css ``` some ``` file_rtl.css ``` some ``` file.rtl.css ``` etc.

**Comment by MohammadYounes** [comment]
I'll add a new option `-e | --ext` which defaults to `.rtl.css`.

**Comment by LyoNick** [comment]
thank you!
