### ISSUE TITLE
Error: Missing required argument #1

### ISSUE THREAD

**Issue by mahmoudmk1** [MohammadYounes/rtlcss#205]
[npm-debug.log](https://github.com/MohammadYounes/rtlcss/files/5684518/npm-debug.log)
Dear Mohammad 
I hope you are doing well
This error occurred while I was trying to deploy **# npm install -g rtlcss**
I think that happened only after the last code-update you have done.
thanks

**Comment by MohammadYounes** [comment]
This is npm related error. What is your node/npm version ?

Update npm and try installing it again.

**Comment by mahmoudmk1** [comment]
![npm](https://user-images.githubusercontent.com/51242024/102019224-e4de2400-3d7a-11eb-9d1b-09cd965653be.jpeg)
I have installed the latest version with
# npm install -g npm@latest
 node v 8.10.0
 npm  v 3.5.2
 but the error still exist for npm with #  npm install -g rtlcss

**Comment by MohammadYounes** [comment]
@mahmoudmk1 rtlcss v3 dropped Node.js **6.x, 8.x, 11.x, and 13.x** versions. You should install v2.6.2

```bash
npm install -g rtlcss@2.6.2
```

**Comment by elblasy33** [comment]
Mohammad  Younes
I have the same problem 
ubuntu 18.04
The problem  from only a few days

**Comment by MohammadYounes** [comment]
@elblasy33 I can't reproduce this, plus the shared log says:

> 642 error typeerror This is an error with npm itself. Please report this error at:
642 error typeerror     <http://github.com/npm/npm/issues>

![image](https://user-images.githubusercontent.com/4712046/102021693-3346ef00-3d8a-11eb-8bf3-a5933a3a12ed.png)

**Comment by elblasy33** [comment]
solved thanks 
npm install -g rtlcss@2.6.2
