### ISSUE TITLE
Add support for scss files

### ISSUE THREAD

**Issue by VadymLazariev** [MohammadYounes/rtlcss#207]
Hello! 

I'm trying to integrate rtlcss into Angular 9 and everything works well with CSS  files in the app, but it totally ignores the scss files in the components.  I tried to create rtl.scss manually through the `rtlcss component.scss  component.rtl.scss` and it worked. It seems like it can work with scss, but I'm not sure how can I make it with -d tag. Do you have any suggestions about it?

**Comment by MohammadYounes** [comment]
@VadymLazariev It might work in case you were using valid `css` syntax. However, `scss` is a superset and may contain language elements not `css` compliant. 

Moreover, `scss` is intermediate and it must be converted to `css`, so the overhead of supporting it is not worth the effort.
