### ISSUE TITLE
4.5.3 on cdn returns 404

### ISSUE THREAD

**Issue by git37** [MohammadYounes/rtlcss#215]
also the download from github

**Comment by thepuzzle** [comment]
Following, I get the same error, ni CDN, no download.

**Comment by MohammadYounes** [comment]
@git37 @thepuzzle No problems from my side, both files download fine

- https://cdn.rtlcss.com/bootstrap/v4.5.3/css/bootstrap.min.css
- https://cdn.rtlcss.com/bootstrap/v4.5.3/js/bootstrap.min.js
