### ISSUE TITLE
RTLCSS value directives when using SASS/SCSS: docs are not clear enough

### ISSUE THREAD

**Issue by nirpeled** [MohammadYounes/rtlcss#221]
On the "Value directives" docs [page](https://rtlcss.com/learn/usage-guide/value-directives/#Tip), there's a tip that says:

```
SASS/SCSS will omit comments placed inside the declaration value from the output CSS.
To preserve RTLCSS value directives, Use SASS interpolation syntax passing your comment as string.
```
with an example:
```css
.example {
  font-size:16px #{"/*rtl:14px*/"};
}
```
but it should actually include a `!` since otherwise it won't work and also a space before the value, a working example will be:
```css
.example {
  font-size:16px #{"/*!rtl: 14px*/"};
}
```
I just spent two days trying to solve this issue and now that I have, let's make it easier for everyone else!

Also, I wanted to issue a PR for this but apparently the docs are not part of the repo, maybe it should be?

Thanks,

Nir

**Comment by MohammadYounes** [comment]
To be updated. However, this only happens when using compressed mode.

> By default, multi-line comments be stripped from the compiled CSS in compressed mode. If a comment begins with /*!, though, it will always be included in the CSS output.
https://sass-lang.com/documentation/syntax/comments#in-scss

**Comment by nirpeled** [comment]
Oh cool!!
Good to know that it was b/c of compressed mode.
Thank you for this awesome library 🚀
