### ISSUE TITLE
Doesn't convert `scaleX(-1)`

### ISSUE THREAD

**Issue by babakfp** [MohammadYounes/rtlcss#238]
Hi

### Describe the problem
```javascript
const rtlcss = require('rtlcss')
console.log(
	rtlcss.process('transform: scaleX(-1)')
)
// Expected: transform: scaleX(1)
```

### What is the use case of ` scaleX(-1)`?
I use it to flip icons on an RTL website. If an emoji tinks with its right eye, in an RTL website, it needs to twice with its left eye.

### Alternatives considered
I'm thinking to remove the `scaleX(-1)` and instead use `html[dir=rtl]` and select the icons and...
this alternative doesn't work if I use the icon as CSS style `font-family, content`:
![Screenshot 2021-09-01 055605](https://user-images.githubusercontent.com/44144724/131674952-71706a1f-f68b-41f1-a160-6293b9dc4b5c.png)

**Comment by MohammadYounes** [comment]
Automatically flipping `scaleX` is dangerous and may cause undesired side effects (especially for text).  For this reason you need to be explicit about it and use a value directive `transform: /*!rtl:scaleX(-1) */'} none;`

**Comment by babakfp** [comment]
This solution doesn't work with sass, so I used my solution instead.

**Comment by babakfp** [comment]
Also, I'm kinda sorry that I didn't look at the docs at first🖤

**Comment by MohammadYounes** [comment]
@babakfp For sass you need to use interpolation syntax as mentioned [here](https://rtlcss.com/learn/usage-guide/value-directives/#Tip)

**Comment by babakfp** [comment]
Hi
Thank you. I'll try it next time. Thank you for such a helpful tool. I'm using some SASS and Tailwindcss, and it do the job only with 1 command👌🏻.
Have a good day/night🖤
