### ISSUE TITLE
.rtlcssrc.json or .rtlcss.json

### ISSUE THREAD

**Issue by Alkarex** [MohammadYounes/rtlcss#247]
Hello,
There is a discrepancy between the code and the documentation regarding the name of the configuration file with explicit JSON extension.

The code says `.rtlcss.json`
https://github.com/MohammadYounes/rtlcss/blob/9e2ee0b1b6fed3b197164f6b1d21b8896e3b33e8/lib/config-loader.js#L7

but the documentation says `.rtlcssrc.json`
![image](https://user-images.githubusercontent.com/1008324/138592806-d27efee8-1342-40e5-be53-8746a463add9.png)

I could not find the source code of the documentation to send a PR, but I can happily send a PR for changing the code if you like.

**Comment by MohammadYounes** [comment]
@Alkarex docs updated. Thanks!
