### ISSUE TITLE
problem with non-static positioning

### ISSUE THREAD

**Issue by omid-khd** [MohammadYounes/rtlcss#25]
hi there is something about rtling a css file that usually is ignored.
when there is a left or right rule for a selector with non-static position in rtl proccessing that rule first : must take auto value. and second must be filliped.ie:
```css
left: 10px;
```
must convert into: 
```css
left: auto;
right: 10px;
```
if not that selector now have 2 rule: 
```css
left: 10px;
right: 10px;
```

**Comment by MohammadYounes** [comment]
Hi,

Seems you are trying to create a smaller RTL version containing only the set of flipped CSS rules. Doing so may give unintended results!  

Unless you can figure out the computed style, a subset of RTL overrides approach will fail. (see [Why make a complete RTL version ?](https://github.com/MohammadYounes/rtlcss/wiki/Why-make-a-complete-RTL-version-%3F))

Thanks.

**Comment by omid-khd** [comment]
making a wordpress theme rtl is in my mind.
to making a rtl.css file for RTLing a wordpress theme it only needs to have a subset of style.css rules.
and in such situations if we don't normalize left and righte rules with auto value  the result is a selector with both left and right value and cause element to move around. from my experience i can tell that it's better in those situations to use auto value.

**Comment by MohammadYounes** [comment]
Adding auto values is not a generic solution and is tied to specific cases. On the other hand, having a complete version is a much safer if you are trying to automate the process.
