### ISSUE TITLE
Can I output changes only?

### ISSUE THREAD

**Issue by Alghamdi** [MohammadYounes/rtlcss#26]
Can I output changes only using CLI?
Wordpress uses rtl.css file for RTL languages, so adding that file instead of changing the main css file is very helpful.

**Comment by MohammadYounes** [comment]
This tool does not support that, as its intended to provide complete automation. Moreover I don't recommend doing so. see [Why make a complete RTL version ?](https://github.com/MohammadYounes/rtlcss/wiki/Why-make-a-complete-RTL-version-%3F)  



Thanks.
