### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by ai** [MohammadYounes/rtlcss#27]
RTLCSS is awesome. I want to use as example of PostCSS power. But I can puut a link, because RTLCSS’s README doesn’t tell what plugin does (many of users doesn’t know what is RTL is).

Maybe you put a CSS input/output example and some before/after screenshot?

**Comment by ai** [comment]
BTW, what is a purpose of “CSS Syntax” section?

**Comment by MohammadYounes** [comment]
Thanks!  I'm kinda bad at documentation ...

> RTLCSS’s README doesn’t tell what plugin does

I thought it was obvious ( I updated the main description).

> what is a purpose of “CSS Syntax” section?

The CSS Syntax helps clarify the names as RTLCSS allows you to change its behavior by implementing your own processing instructions or directives on rule, declaration and property level. 

For example, I used it [here](https://github.com/MohammadYounes/AlertifyJS/blob/master/Gruntfile.js#L55-L75) to prefix all rules:
```css
.dialog { ... } 
```
becomes :
```css
.ajs-dialog { ...}
```

> Maybe you put a CSS input/output example and some before/after screenshot?

The documentation requires complete revision indeed! Also the lib itself (thinking RTLCSS 2) ... but I just can't find the time. 

Have seen the wiki ?

- [Why AutoRename ?](https://github.com/MohammadYounes/rtlcss/wiki/Why-Auto-Rename%3F)

- [Why make a  complete RTL version ?](https://github.com/MohammadYounes/rtlcss/wiki/Why-make-a-complete-RTL-version-%3F)

**Comment by MohammadYounes** [comment]
@ai plz check the updated [README](https://github.com/MohammadYounes/rtlcss/blob/master/README.md) and let me know your thoughts!

**Comment by ai** [comment]
@MohammadYounes much better, but we have some problems:

* `CSS Syntax` section should not be in most important top part of README. These top sections is for project overview and exmaples. Not for details.
* Can you make a screenshop of some real site (maybe in mobile version with small width) `before` and `after` RTLCSS. Current border examples is confused, because it is easy to misss border changes.

**Comment by MohammadYounes** [comment]
@ai Thanks for the input,  [README](https://github.com/MohammadYounes/rtlcss/blob/master/README.md) updated.

**Comment by ai** [comment]
@MohammadYounes awesome!

Can I ask about one more fix (I think it will make README more cute) :).

Can you cut browser window around GitHub screenshot (it is too bright) and put screenshots side by side (you can use `align=right` and `alight=left` in `<img`)

**Comment by ai** [comment]
I put link to your plugin to PostCSS features examples :)

**Comment by MohammadYounes** [comment]
Thanks! I added a quick access menu and resized the images so they would fit side by side, let me know if the browser window still needs to be removed or not!

**Comment by ai** [comment]
Now RREADME looks perfect :D

**Comment by MohammadYounes** [comment]
Thanks ;)
