### ISSUE TITLE
rtl css not compatible with devextreme dxdatagrid

### ISSUE THREAD

**Issue by mbtolou** [MohammadYounes/rtlcss#275]
I created a repository to test the dxdatagrid

There was no way I could match the dxdatagrid and the rtlcss.
Can you help me solve the problem?

https://github.com/mbtolou/devextreme_rtlcss

**Comment by MohammadYounes** [comment]
devexpress already provide right-to-left support 

see: 
- https://js.devexpress.com/Documentation/Guide/Common/Localization/#Right-to-Left_Support
- https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/RightToLeftSupport/jQuery/Light/

**Comment by mbtolou** [comment]
yes 

but when use devexpress with quasar rtl, conflicted.
i am generate sample to show problem .
