### ISSUE TITLE
Allow to control main rtl/ltr selector prefix

### ISSUE THREAD

**Issue by Tal500** [MohammadYounes/rtlcss#277]
I think it will be great if you'd have the option to control the rtl/ltr selector prefix.
Today, for each relevant rule, RTLCSS outputs for a rule starting with [dir="ltr"] and another starting with [dir="rtl"].

I suggest to have the option to control these global prefix, to allow the user to override them. E.G:
* Allow the user to have other global prefixes like .ltr and .rtl
* In many css/frontend frameworks, there is the concept of :global(...) selector modifier. Specifcally, in Svelte, due to the scoping system for every component, the outputed prefixes [dir=...] doesn't apply to the "dir" attribute in the <body> element. The fix for it is simple - use :global([dir=...]) prefixes instead, which avoid the scoping system. Therefore, if this overriding prefixes option will be available, it will trivially solve these problems.

**Comment by MohammadYounes** [comment]
> Today, for each relevant rule, RTLCSS outputs for a rule starting with [dir="ltr"] and another starting with [dir="rtl"].

I think you are confusing this with another library as rtlcss doesn't add any prefixes.
