### ISSUE TITLE
طريقة التثبيت

### ISSUE THREAD

**Issue by alpipopa** [MohammadYounes/rtlcss#278]
ممكن طريقة التثبيت لو سمحت فيديو

**Comment by mshannaq** [comment]
لتثبيت
rtlcss
يمكنك مراجعة الخطوات على الرابط التالي
https://rtlcss.com/learn/usage-guide/install/
علما بانه يتوجب ان يتوفر لديك دعم ل 
nodejs 
من اجل استخدام
npm 

حيث انه يتوجب فقط تنفيذ الامر
npm install -g rtlcss
على طرفية لينكس

بعدها في حال التركيب كل ما عليك هو تنفيذ الامر
rtlcss
من اجل مناداة الاداة

**Comment by alpipopa** [comment]
Thanks
