### ISSUE TITLE
Support for flexbox properties

### ISSUE THREAD

**Issue by necolas** [MohammadYounes/rtlcss#28]
As layout with flexbox becomes more common, RTL support for flexbox properties will be useful. For example, reversing the `flex-direction` and content alignment.

**Comment by MohammadYounes** [comment]
Flexbox properties follow writing direction and do not require flipping. For example:

**flex-direction**
* `row` (default): left to right in ltr; right to left in rtl
* `row-reverse`: right to left in ltr; left to right in rtl

**flex-wrap**

* `nowrap` (default): single-line / left to right in ltr; right to left in rtl
* `wrap`: multi-line / left to right in ltr; right to left in rtl
* `wrap-reverse`: multi-line / right to left in ltr; left to right in rtl

Thanks.

**Comment by necolas** [comment]
oh nice! thanks for teaching me something :)
