### ISSUE TITLE
can not convert .css file to rtl.css

### ISSUE THREAD

**Issue by starlitnight** [MohammadYounes/rtlcss#283]
in VScode i can't use the cli command starting with $
![21ca95df-9873-4d6c-a06e-32fda9fda85b](https://user-images.githubusercontent.com/6129938/154096357-8235254e-a07f-42d7-96a4-e3c3a10f3edf.jpg)

**Comment by MohammadYounes** [comment]
If you want to use it from the command line, you must install it globally `npm i -g rtlcss`. 

Locally installed package can be run using `package.json` scripts. For example 
```json
 ...
 "scripts": {
    "rtlcss": "rtlcss ./build/styles.css ./build/styles.rtl.css"
  }
 ...
```

Then you can run `npm run rtlcss`.
