### ISSUE TITLE
How the --directory flag is work 

### ISSUE THREAD

**Issue by HJS-dev** [MohammadYounes/rtlcss#288]
Hi Mr.Mohammed I wonder If you can Explain if is there was a way to --watch a bunch of *_files.scss components all together, and return
processed rtl file in real-time instead of doing one file by the time.

I would love to mention that I tried the method in the documentation section, and it's not working in my project, maybe I miss something

**Comment by HJS-dev** [comment]
Hi, Good morning everyone, I see now that the method "--directory" is only working with "ex.css", not with SASS or SCSS.


Please correct me if I'm doing this wrong thank you

**Comment by MohammadYounes** [comment]
@HJS-dev Watching files is out of the scope of this tool, you may try https://github.com/doowb/watch-cli

RTLCSS is a POSTCSS plugin, it converts CSS, not SCSS. You need to compile the SCSS to CSS before running it through RTLCSS.
