### ISSUE TITLE
Converting .scss files using rtlcss

### ISSUE THREAD

**Issue by okaeiz** [MohammadYounes/rtlcss#289]
Hi there!
We are developing a massive amount of scss source files of Nextcloud and we need to change the interface direction to RTL.
We have found RTLCSS tool and wish that it's useful.
But we don't know how to convert scss files using rtlcss.

**Comment by MohammadYounes** [comment]
@okaeiz RTLCSS is a POSTCSS plugin, it converts CSS, not SCSS. You need to compile the SCSS to CSS before running it through RTLCSS.

**Comment by okaeiz** [comment]
how can we do this? We're stuck!

**Comment by MohammadYounes** [comment]
@okaeiz It totally depends on how you build your SCSS. You can have this as a post build process to convert the final CSS files.
