### ISSUE TITLE
How to call RTLcss to convert a LTRcss file to RTLcss?

### ISSUE THREAD

**Issue by ankitsingh600** [MohammadYounes/rtlcss#290]
I have a LTRcss file written for nextjs, i want to convert that file to RTLcss. How can we achieve that using your package.

**Comment by MohammadYounes** [comment]
You can follow [usage guide](https://rtlcss.com/learn/usage-guide/install/) / [CLI](https://rtlcss.com/learn/usage-guide/cli/). Or you can integrate into your build process, as this is a standard postcss plugin. For example, if you are using webpack, you can simply convert the output css by [adding](https://github.com/rsuite/rsuite.github.io/blob/master/webpack.config.js#L221) a [plugin](https://github.com/rsuite/rsuite.github.io/blob/master/scripts/RTLCSSPlugin.js).
