### ISSUE TITLE
Vite & cssRTL Plugin

### ISSUE THREAD

**Issue by prfardin** [MohammadYounes/rtlcss#294]
Can You Help me how Vite and [RTlCSS](https://github.com/MohammadYounes/rtlcss) should be set?

**Comment by MohammadYounes** [comment]
I haven't worked with vite.  However, You may follow the guide on how to use postcss plugins 
https://vitejs.dev/guide/features.html#postcss

**Comment by prfardin** [comment]
> I haven't worked with vite. However, You may follow the guide on how to use postcss plugins https://vitejs.dev/guide/features.html#postcss

Thank You
