### ISSUE TITLE
Ignore import not working

### ISSUE THREAD

**Issue by siamak2** [MohammadYounes/rtlcss#296]
Hi
My problem is exactly like https://github.com/MohammadYounes/rtlcss/issues/113 but the solution is not working for me.
I'm using laravel mix that underneath is using webpack and postcss
I tried the solution in above issue:
```
rtl-begin-ignore.css:
/*rtl:begin:ignore*/

rtl-end-ignore.css:
/*rtl:end:ignore*/
```
And used it like this:
```scss
@import "rtl-begin-ignore.css";
@import "~toastr/build/toastr.css";
@import "rtl-end-ignore.css";
```
But rtlcss gives this error:
```
WARNING in ./resources/sass/rtl-begin-ignore.css
(1:1) rtlcss: unclosed directive "ignore".
```

**Comment by siamak2** [comment]
I found a dirty solution to fix it for now.
In `webpack.mix.js`:
```javascript
const mix = require( 'laravel-mix' );
const fs = require( 'fs' );

mix.before( function () {
	let data = fs.readFileSync( 'node_modules/toastr/build/toastr.css' );
	data = "/*rtl:begin:ignore*/\n" + data + "\n/*rtl:end:ignore*/";
	fs.writeFileSync( 'resources/sass/toastr.css', data );
} )
```

In `resources/sass/app.scss`:
```scss
@import "toastr.css";
```
But I'm hoping that you would fix the warning so I can remove this dirty workaround.

**Comment by MohammadYounes** [comment]
@siamak2 You need not to process each file alone. The idea is to have the content placed between the directives then process the final file only.

Your workaround works too.

**Comment by siamak2** [comment]
I'm not processing each file alone.
I have one `app.scss` file that imports other styles. I just don't want rtlcss process specific file which in this case is `toastr.css`. because that file already have rtl support and rtlcss will revert everything.
I tried this but it didn't worked:
```scss
/*rtl:begin:ignore*/
@import "~toastr/build/toastr.css";
/*rtl:end:ignore*/
```
I know I can run rtlcss from command line on the generated css but I need laravel mix to recognize output file (for cache busting and file watcher)

**Comment by MohammadYounes** [comment]
This is not a problem with rtlcsss. Check the output file being passed to rtlcss, does it contain 

```css
/*rtl:begin:ignore*/
... content of toastr.css 
/*rtl:end:ignore*/
```

or 

```css
/*rtl:begin:ignore*/
/*rtl:end:ignore*/
... content of toastr.css 
```

?
