### ISSUE TITLE
more options as `false` by default

### ISSUE THREAD

**Issue by necolas** [MohammadYounes/rtlcss#3]
This plugin is quite aggressive in what in changes in selectors and urls. I think almost all the options should be `false` by default, especially `swapLeftRightInUrl`, `swapLtrRtlInUrl`, `swapWestEastInUrl`, and `autoRename` because you have to intentionally agree to those conventions for it to work for you. I don't think we'd have use for `autoRename` at Twitter; that one seems particularly tied to one way of writing CSS.

It might be nice to merge the url options into a single one that takes a map of strings to swap (i18n friendly too, as people can define their own non-english words if necessary).

**Comment by MohammadYounes** [comment]
@necolas  v2.0 is out with more options as `false` by default :)
