### ISSUE TITLE
Remove non-override code

### ISSUE THREAD

**Issue by narimanadam** [MohammadYounes/rtlcss#30]
Hello there, 

Firstly, I would like to thank you for the great plugin it make things easier to build an rtl version of any css file. 

Secondly, I would like to suggest a feature or a flag that only export the reflected rules/properties only into the output file instead exporting all the rules/properties into the output file. Some CMSs e.g Drupal uses the convention of `style.css` for all `ltr` languages and `style-rtl.css` for `rtl`, basically when viewing the drupal site as a ltr language the style.css only is called and if viewing the site using a rtl language the `style.css` get included first and the `style-rtl.css` get included second where the rtl file only overrides the properties that needs to be reflected to rtl. That option will benefit such systems without any need to remove the original style.css file from the rtl version. 

It will be great if we could have an option to export only the overridden css properties, I am using [gulp-rtlcss](https://github.com/jjlharrison/gulp-rtlcss) with less to compile my css. 

Thank You.

**Comment by MohammadYounes** [comment]
This tool is intended to provide complete automation. The override approach will most probably require manual intervention. see [Why make a complete RTL version ?](https://github.com/MohammadYounes/rtlcss/wiki/Why-make-a-complete-RTL-version-%3F)  

>Duplicate #13 and #26 

Thanks.
