### ISSUE TITLE
Bootstrap 5.2 LTR and RTL at the same time (scss with Laravel vite)

### ISSUE THREAD

**Issue by Ahmed-Elrayes** [MohammadYounes/rtlcss#301]
Hello, i'm trying to use bootstrap with both RTL and LTR in the same scss file (as described in here [LTR and RTL at the same time](https://getbootstrap.com/docs/5.2/getting-started/rtl/#ltr-and-rtl-at-the-same-time)
```scss
/* rtl:begin:options: {
  "autoRename": true,
  "stringMap":[ {
    "name": "ltr-rtl",
    "priority": 100,
    "search": ["ltr"],
    "replace": ["rtl"],
    "options": {
      "scope": "*",
      "ignoreCase": false
    }
  } ]
} */
.ltr {
  @import "../node_modules/bootstrap/scss/bootstrap";
}
/*rtl:end:options*/
```
But for some reason it doesn't seem to be working, i'm not sure whether i'm using it incorrectly or smth
as in Laravel all what we need to build the css..etc is using this command `npm run build` but it doesn't build .rtl class
so i thought i might need to implement this in my postcss.config.js
```ts
const rtlcss = require("rtlcss");
module.exports = {
    plugins: [
        rtlcss(),
    ]
}
```
this one works but there is no more .ltr class working,instead it shows errors in css
![image](https://user-images.githubusercontent.com/30704271/196003626-5a955bb6-a21d-4266-8027-588da7714408.png)
so there is now only .rtl but fully incorrect 
as you can see
![image](https://user-images.githubusercontent.com/30704271/196003671-91f50d7a-3514-47a8-b7b8-67013e81a66c.png)

This is how it works like in .ltr (without using rtlcss())
![image](https://user-images.githubusercontent.com/30704271/196003713-609d3830-8ded-40c9-bbc2-0bc2cb2fc417.png)

Actually i should post this issue in Laravel or Vite but no one seem to be able to help, hope fully you can find a solution for me.

**Comment by MohammadYounes** [comment]
Based on this image
![image](https://user-images.githubusercontent.com/4712046/196030699-d6600123-e1b6-4678-a630-37a0989ce14b.png)

It seems you placed this in the  CSS file instead of the SCSS. As the output file should prepend `.ltr` / `.rtl` to every selector you have.

**Comment by Ahmed-Elrayes** [comment]
nah actually it's a .scss file as you can see
![image](https://user-images.githubusercontent.com/30704271/196032129-2984b256-d5a3-4f6f-87e2-37b7c01435f1.png)

**Comment by MohammadYounes** [comment]
Check the output CSS file. What content does it have ?

**Comment by Ahmed-Elrayes** [comment]
![image](https://user-images.githubusercontent.com/30704271/196032728-7ce55e81-2d54-4d11-97cf-2791d597847d.png)
since the file is too big i will attach it.
https://drive.google.com/file/d/1lnjSlRAAuXOHeGdF6MHWEx0l0GNpVPvG/view?usp=sharing

**Comment by MohammadYounes** [comment]
You have a bad CSS at the beginning of the output file

![image](https://user-images.githubusercontent.com/4712046/196033203-4f84a635-5e8b-42d6-8f21-eb54c1f1ff31.png)

**Comment by Ahmed-Elrayes** [comment]
as you see, i'm only compiling the bootstrap 5.2 from node modules.

**Comment by MohammadYounes** [comment]
disable rtlcss and check the output file.

**Comment by Ahmed-Elrayes** [comment]
when i disable it, it works properly.

**Comment by MohammadYounes** [comment]
I don't have your setup, You need to debug the source of the issue. As I doubt this has anything to do with rtlcss.

**Comment by Ahmed-Elrayes** [comment]
thought so, i don't think it will work like that, thanks at least is there a way to get rtl scss data? because i use custom variables so i wanna combine it like i can combine bootstrap normally, doesn't matter whether i will create two separate css files or not.

**Comment by Ahmed-Elrayes** [comment]
btw, rtlcss automatically work even if i don't add this string map.
```scss
/*rtl:begin:options: {
  "autoRename": true,
  "stringMap":[ {
    "name": "ltr-rtl",
    "priority": 100,
    "search": ["ltr"],
    "replace": ["rtl"],
    "options": {
      "scope": "*",
      "ignoreCase": false
    }
  } ]
} */

.ltr{
@import "file";
}
/*rtl:end:options*/

**Comment by Ahmed-Elrayes** [comment]
ok, i found a solution i will share here in case someone got the same issue.

inside postcss config file i added these 

```js
const postcssRTLCSS = require('postcss-rtlcss');
const {Mode, Source, Autorename} = require('postcss-rtlcss/options');

// inside the plugins i added postcssRTLCSS()
module.exports = {
    plugins: [
        postcssRTLCSS(),
    ]
}
```

and in my .scss file i removed the class .ltr

and now it works great both in the same file and the string map works great.

**Comment by abumosaab** [comment]
Thanks. Seems to be working with Laravel...

First install ``postcssRTLCSS`` using:
```javascript
npm install -D postcss-rtlcss
```
Then modified  `vite.config.js` file to be like this:
```javascript
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import postcssRTLCSS from 'postcss-rtlcss'; // <<< HERE

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/sass/app.scss',
                'resources/js/app.js',
            ],
            refresh: true,
        }),
        postcssRTLCSS() // <<< AND HERE
    ],
});
```
Of course you need to rebundle assets after each change using:
```shell
# Run the Vite development server...
npm run dev
 
# Build and version the assets for production...
npm run build
```

**Comment by Ahmed-Elrayes** [comment]
as for now it works me like that https://github.com/MohammadYounes/rtlcss/issues/326#issuecomment-1937757651
