### ISSUE TITLE
using blacklist

### ISSUE THREAD

**Issue by CyberDepot** [MohammadYounes/rtlcss#303]
Hi  
im using metronic and that's use webpack-rtl-plugin witch that use your plugin  
i need skip rtl for some plugin, class or file  
but i cant use black list  
please give me a sample code  
i use this code    
but doesn't work

```
    plugins.push(new WebpackRTLPlugin({
        filename: '[name].rtl.css',
        options: {
            'blacklist': {
                "sweetalert2": {
                    "config":true
                }
            }
        },
        plugins: [],
        minify: false,
    }));
```

**Comment by MohammadYounes** [comment]
black list is used to disable directives only. For example `{"rtlcss":{"config":true}}` this black list disables the [`config`](https://rtlcss.com/learn/usage-guide/control-directives/#Config) directive inside rtlcss plugin.

**Comment by CyberDepot** [comment]
hi thank you
i need a command for disable rtl on a css file like this

```
@import "../plugins/toastr/build/toastr.css";

/*rtl:begin:ignore*/
@import "~sweetalert2/dist/sweetalert2.css";
/*rtl:end:ignore*/

@import "~line-awesome/dist/line-awesome/css/line-awesome.css";
```

but that's doesent work

**Comment by MohammadYounes** [comment]
@CyberDepot try the the solution mentioned here https://github.com/MohammadYounes/rtlcss/issues/113#issuecomment-379907981
