### ISSUE TITLE
Unknown word error when "//' is used for commenting in scss files.

### ISSUE THREAD

**Issue by rakris01** [MohammadYounes/rtlcss#315]
CssSyntaxError: <FilePath>/Filename.scss:12:6: Unknown word
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser

  10 | /* Modal */
  11 | body.ReactModal__Body--open {
> 12 |   // Prevent page scrolling when modal is open
     |      ^
  13 |   overflow: hidden;
  14 | }

RTCLSS CLI
Command used: rtlcss <ltrfilename> <rtlfilename>.
rtlcss: Warning! No config present, using defaults.

**Comment by MohammadYounes** [comment]
as the error says `You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser`.
rtlcss accepts css only.
