### ISSUE TITLE
issue with media queries and onlyDiff option

### ISSUE THREAD

**Issue by Aleksandr0114** [MohammadYounes/rtlcss#325]
I have problem with onlyDiff option.
Example:
.header_search.search_standard .header_search-field .search-field {
  width: 270px;
}
@media (max-width: 767px) {
    .header_search.search_standard .header_search-field {
      right: 0;
      left: auto;
    }
  }

Media queries disappear when OnlyDiff is enabled. And return this code:
.header_search.search_standard .header_search-field .search-field {
  width: 270px;
}

Can you fix it?

**Comment by MohammadYounes** [comment]
rtlcss does not have such an option `onlyDiff`. You should report this to the repo of the tool you are using.
