### ISSUE TITLE
Support Flex

### ISSUE THREAD

**Issue by jlukic** [MohammadYounes/rtlcss#33]
Hi, thanks as always Mohammad for your hard work with RTLCSS. 

Since we swapped many components to `flex` in 2.0, I've noticed rtlcss does not modify flex positioning rules. Would you consider adding support for swapping rules like [`flex-direction`](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-direction) and `align-items` in rtlcss?

**Comment by MohammadYounes** [comment]
Hey Jack,

Flexbox properties follow writing direction and do not require flipping.

Dup. #28
