### ISSUE TITLE
Tabbed menu not compatible

### ISSUE THREAD

**Issue by ashraf21c** [MohammadYounes/rtlcss#332]
Hello,
I tried applying RTL to [this tab nav](https://www.w3schools.com/howto/howto_js_hover_tabs.asp), but it doesn`t work.

This is the output:

```
/*CssSyntaxError: <css input>:92:3: Unknown word

  90 | <script>
  91 | function openCity(evt, cityName) {
> 92 |   var i, tabcontent, tablinks;
     |   ^
  93 |   tabcontent = document.getElementsByClassName("tabcontent");
  94 |   for (i = 0; i < tabcontent.length; i++) {
*/
```

**Comment by MohammadYounes** [comment]
For rtlcss to work, it requires a valid CSS.

**Comment by ashraf21c** [comment]
> For rtlcss to work, it requires a valid CSS.

Already tried 
CSS
.element { direction: rtl; }

and HTML
<html dir="rtl">...</html>

Any alternative CSS code??
Thank you.

**Comment by ashraf21c** [comment]
As far as I know, only the person who asks marks the thread as resolved/ closed.
The problem isn't fixed yet.

**Comment by ashraf21c** [comment]
This is an old post.. thank you for your reply.
I already sussessfully used my same code in a page I created and published myself. However, it doesn't work here.
This is not CSS problem, or this platform requires a specific css code.

**Comment by MohammadYounes** [comment]
The CSS in the link you provided can be converted using RTLCSS without any issues 

![image](https://github.com/MohammadYounes/rtlcss/assets/4712046/d86b4275-08eb-4e09-82c7-df82abc81ca4)

Moreover, the error you included has nothing to do with RTLCSS.

So how can I help you ?

**Comment by ashraf21c** [comment]
I'm sorry.
I commented to some flat file CMSs for not supporting RTL.
Now I remember what this specific one is.
I'll investigate and try again.
Thank you very much.
Best regards.

**Comment by ashraf21c** [comment]
I tested the output of RTLCSS for mentioned link.
Kindly see here: https://codepen.io/ashraf21c/pen/KKJmWLx
The tabs are no longer clickable unless I remove the CSS code.
I don`t know why this happens.

This is another one, works fine, my edit
Ver 1: https://codepen.io/ashraf21c/pen/VwqqdYp (most similar to the link`s)
Ver 2: https://codepen.io/ashraf21c/pen/BaMBxdV (adds letter spacing prevention, because it happened in some environments).

As for my understanding, the output of RTLCSS should work, let us say like version 1.. just converting to RTL..
However, this doesn`t happen. Yes, it flipped like a mirror, but **generated output causes it to crash (items not clickable)**.
This is why I`m posting this.
I think something can be improved here to fix this. (so that the output file works without manual edits)

I`m attaching input and ouput CSS files. (I changed the extension to txt so that I can upload them here)
[original - input.txt](https://github.com/MohammadYounes/rtlcss/files/13313366/original.-.input.txt)
[generated output.txt](https://github.com/MohammadYounes/rtlcss/files/13313367/generated.output.txt)

Best Regards,
