### ISSUE TITLE
After compilation, ignore is invalid

### ISSUE THREAD

**Issue by ok-jojo** [MohammadYounes/rtlcss#336]
After the order of styles is changed after compilation, the position of `ignore` also changes, and the styles that should be ignored are not ignored.
![img_v3_0258_cafb3947-a08f-4fed-8648-148db298183h](https://github.com/MohammadYounes/rtlcss/assets/133937909/9da7ba9f-15b9-41eb-a229-6a1ba7d9f8e5)

**Comment by MohammadYounes** [comment]
This is related to less compilation. Not rtlcss.
