### ISSUE TITLE
Ignore another props

### ISSUE THREAD

**Issue by abouolia** [MohammadYounes/rtlcss#36]
Is there an option to ignore another props which have noting to do to rtl?

For example 
```
.selector{
background: red;
 display:inline-block;
padding:5px 10px 15px 20px;
}
```

OUTPUTS

```
.selector{
padding:5px 20px 15px 10px;
}
```

Thanks :)

**Comment by MohammadYounes** [comment]
This tool does not support that, as its intended to provide complete automation.  see [Why make a complete RTL version ?](https://github.com/MohammadYounes/rtlcss/wiki/Why-make-a-complete-RTL-version-%3F)  

Thanks :)

>Duplicate #13, #26,  #30 and #34
