### ISSUE TITLE
CLI: Support for input source maps

### ISSUE THREAD

**Issue by wkornewald** [MohammadYounes/rtlcss#40]
Maybe I've missed sommething, but input source maps don't seem to be taken into account. Our compiled Sass code has a source map, but rtlcss only maps back to the Sass' CSS output instead of the original Sass files.

Also, the generated source map file only contains the text "undefined" and the source map itself is inlined as a data URI in the output CSS.

**Comment by MohammadYounes** [comment]
>  but rtlcss only maps back to the Sass' CSS output instead of the original Sass files.

This is the expected behavior, since SASS CSS output is RTLCSS input.

> the generated source map file only contains the text "undefined" and the source map itself is inlined as a data URI in the output CSS.

As of postcss 3.0 `map.inline` is enabled by default, which will cause source maps to be embedded inside the processed file, you need to explicitly set it to `false`.

```js
 rtlcss([...]).process(css, {
    from: 'ltr.css',
    to:   'rtl.css',
    map: { inline: false },
});
```

**Comment by wkornewald** [comment]
> > but rtlcss only maps back to the Sass' CSS output instead of the original Sass files.

> This is the expected behavior, since SASS CSS output is RTLCSS input.

However, the Sass output also contains a source map, so it would be possible to map back to the original source, which makes debugging much easier. Currently we have to grep the whole project because we have lots of small Sass modules. Other tools like Uglify support reusing intermediate source maps, too (e.g. so you can see the original Coffee source instead of some unreadable Coffee compiler output).

> As of postcss 3.0 map.inline is enabled by default, which will cause source maps to be embedded inside the processed file, you need to explicitly set it to false.

I forgot to mention, we're using the cli (via a custom build system written in Python). The cli's source map output seems to be broken. If the source map is supposed to be inline, why does it generate a .map file with "undefined"? Otherwise the cli should set inline: false.

**Comment by MohammadYounes** [comment]
> so it would be possible to map back to the original source

Sure, but still you need to pass the previous source map too
```js
rtlcss([...]).process(css, {
    from: 'ltr.css',
    to:   'rtl.css',
    map: { 'inline': false, 'prev': previousMap },
});
```
> The cli's source map output seems to be broken. If the source map is supposed to be inline, why does it generate a .map file with "undefined"? Otherwise the cli should set inline: false.

True, the CLI was written prior to postcss 3.0 release, it should be updated to set `inline:false`.


However, to make sure the fix will solve your problem, can you try running your build with a modified version of the CLI. Just update [this line](https://github.com/MohammadYounes/rtlcss/blob/1.6.2/bin/rtlcss.js#L159) to: 

```js
    opt.map = {inline:false, prev:true};
```

And make sure your [config](https://github.com/MohammadYounes/rtlcss/blob/master/CLI.md#config) has `map:true`.

Thanks.

**Comment by MohammadYounes** [comment]
@wkornewald According to my tests, when the processed CSS file contains a reference to an external map file then setting `map` config option to true is sufficient enough. Otherwise you need to set it to `{inline:false}`.

**Comment by wkornewald** [comment]
@MohammadYounes Thanks. I've updated our build system and now it seems to work fine. The only issue left is that apparently on Windows there is a mixture of line endings in the generated css file. The code has \r\n, but the sourceMappingURL annotation comment uses \n.

**Comment by MohammadYounes** [comment]
That's caused by [postcss](https://github.com/postcss/postcss), see [this line](https://github.com/postcss/postcss/blob/master/lib/map-generator.es6#L138).
