### ISSUE TITLE
Auto rename will work only for declartion

### ISSUE THREAD

**Issue by saman-php** [MohammadYounes/rtlcss#43]
```
var rtlcss = require('rtlcss');

var result = rtlcss.process(".text-right { text-align: right; }");
```
But the result is: ```.text-right { text-align: left; };```
As you see the selector name will not change on the process

**Comment by MohammadYounes** [comment]
Yes, this is the expected behavior. `AutoRename` Applies to CSS rules containing no directional properties, it will update the selector by applying String Map.

In your example, the rule contains a directional property 'text-align:right', thus the rule will not be renamed.

If you want to force renaming of this rule, you can use the `rename` directive:

```js
var rtlcss = require('rtlcss');

var result = rtlcss.process("/*rtl:rename*/.text-right { text-align: right; }");

//output: .text-left { text-align: left; }
```

Thanks!

**Comment by MohammadYounes** [comment]
@saman-php  For a more detailed explanation of **AutoRename** see [Why Auto Rename?](https://github.com/MohammadYounes/rtlcss/wiki/Why-Auto-Rename%3F)

**Comment by saman-php** [comment]
Is there any way to force group of selector to rename?, Because i have lots of this selectors
Thanks!

**Comment by MohammadYounes** [comment]
Currently no, may be in v2.

The point is to keep a single markup that serves both LTR and RTL versions, for example:

* LTR CSS
```CSS
.text-right { text-align: right; }
```
* RTL CSS
```CSS
.text-right { text-align: left; }
```
* HTML
```HTML
<p class="text-right"> Some text </p>
```

The paragraph text will be right aligned when LTR CSS is used, and left aligned when the RTL CSS is used. This way you have only one HTML source that serves both.


You say you have lots of selectors that are directional and requires renaming, Can you provide a live example presenting your use case ?
