### ISSUE TITLE
Selectors with directional substring are not being renamed

### ISSUE THREAD

**Issue by tomericco** [MohammadYounes/rtlcss#44]
Hi,
I'm new to this library, and I can't understand how I turn on selector renaming (from the docs I understood it's given by default, but I can't make it work).

For example:
`rtlcss.process(".navbar-right { float: right !important; }", {greedy: true});`
Will create the following:
`.navbar-right { float: left !important; }`

The value is being converted, but the selector isn't.
I would like the above example to create this string:
`.navbar-left { float: left !important; }`

How can it be? Am I doing something wrong?

Thanks,
Tomer

**Comment by MohammadYounes** [comment]
This is the expected behavior. see the answer for #43. And for more detailed explanation of `AutoRename` see [Why Auto Rename?](https://github.com/MohammadYounes/rtlcss/wiki/Why-Auto-Rename%3F)

**Comment by tomericco** [comment]
Well, I got your point.
My app was designed with many CSS selectors containing: `html[dir=rtl]`, so I need now to remove these rules and align with your RTL conversion rules.

Thanks for the lovely library that you have built.

Tomer
