### ISSUE TITLE
Issue when css has some errors (May be unrelated)

### ISSUE THREAD

**Issue by jawadsahil** [MohammadYounes/rtlcss#45]
I came across a strange issue that may be of interest to you or may be someone else can face such issue and come here and will find it useful.

I am using SASS for my css, and there was some [typo in a file I included](https://github.com/videojs/video.js/issues/2793)... The source css generated was as follows:

    .something {
        background: ligthen(#eee, 25%);
    }
    /* some more css here */
    .elm1{
        background : url('../img/abc.jpg');
    }
    /* some more css here */
    .elm2{
         background : #666;
     }

Now I applied RTLCSS on this file... and the result was strange. All background attributes were shifted. and the declaration with typo was containing a temp in it. i.e. 

    .something {
        background: ligthen(temp, 25%);
    }
    /* some more css here */
    .elm1{
        background : #eee;
    }
    /* some more css here */
    .elm2{
        background : url('../img/abc.jpg');
    }

Though removing the error in css solved the issue, but at least RTLCSS should not propagate the error in a strange way .. :)

Thanks

**Comment by MohammadYounes** [comment]
It's a bug, thanks for reporting this!
