### ISSUE TITLE
Use rtlcss with Grunt

### ISSUE THREAD

**Issue by LeusMaximus** [MohammadYounes/rtlcss#46]
Hi. Can you help me to use rtlcss with [grunt-postcss](https://github.com/nDmitry/grunt-postcss) ? How to set settings?

**Comment by MohammadYounes** [comment]
Similar to the way you [combine it](https://github.com/MohammadYounes/rtlcss#advanced-usage) with other postcss plugins:

```js
//add this to the processors array
require('rtlcss')([options , rules, declarations, properties]).postcss
```

Try it and let me know if it works out?

**Comment by MohammadYounes** [comment]
Another alternative is to use [grunt-rtlcss](https://github.com/MohammadYounes/grunt-rtlcss)

**Comment by LeusMaximus** [comment]
I don't understand how set input and output files in [grunt-postcss](https://github.com/nDmitry/grunt-postcss).

**Comment by LeusMaximus** [comment]
rtlcss and grunt-rtl working the same way?

**Comment by MohammadYounes** [comment]
Setting input and output is a grunt configuration, see grunt documentaion for [Files](http://gruntjs.com/configuring-tasks#files) and [Building the files object dynamically](http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically).

As For [grunt-rtlcss](https://github.com/MohammadYounes/grunt-rtlcss) it's a grunt plugin specific to rtlcss.
