### ISSUE TITLE
Renaming of Selector with "right" or "left"

### ISSUE THREAD

**Issue by willbowling** [MohammadYounes/rtlcss#53]
Hey. there may be a workaround but my selector is getting overwritten using the gulp rtlcss package. 
Is this a bug?
Is there a way to suppress this without having to use rtl:ignore or having to change my classname?

ie.

    /*rtl:rename*/
    .glomo-right-now
        width: 305px
gets renamed to:

    .glomo-left-now
        width: 305px

Thanks in advance.

**Comment by MohammadYounes** [comment]
Hi,

Do you want the class to be renamed or not ?  


If you are running with the default options, then no need to use `'/*rtl:rename*/` on rules having NO directional declarations.

For example:

```js
require("rtlcss").process('.glomo-right-now{ width: 305px}')
// result ==> .glomo-left-now{ width: 305px}
```

Adding `'/*rtl:rename*/` will do a second rename: 

```js
require("rtlcss").process('/*rtl:rename*/.glomo-right-now{ width: 305px}')
// result ==> .glomo-right-now{ width: 305px}
```

But if you disable `autoRename`, then you need to use `'/*rtl:rename*/` :
```js
require("rtlcss").process('/*rtl:rename*/.glomo-right-now{ width: 305px}',{autoRename:false})
// result ==> .glomo-left-now{ width: 305px}
```

Thanks!

**Comment by MohammadYounes** [comment]
closing due to lack of info...

**Comment by lordjoo** [comment]
I need to ignore the renaming for the selectors, How can I do that ?
