### ISSUE TITLE
Is there a way to rename each css class?

### ISSUE THREAD

**Issue by prolink007** [MohammadYounes/rtlcss#55]
I would like to add a ".rtl" to the name of all my classes that are generated with the rtlcss tool, is there a way to do this with the rtlcss tool?

Thanks

**Comment by MohammadYounes** [comment]
Not directly! But you can [create a plugin](https://github.com/MohammadYounes/rtlcss/blob/master/docs/writing-a-plugin.md) to do this. Which version of rtlcss  are you using ... 1.x or 2.x ?

Moreover, If your target is to create a combined LTR/RTL stylesheet? see [postcss-rtlcss-combined](https://github.com/rtsao/postcss-rtlcss-combined)

Thanks!

**Comment by prolink007** [comment]
Thanks for the link, that helped us out.
