### ISSUE TITLE
Semantic UI problem with pointing labels

### ISSUE THREAD

**Issue by mjnaderi** [MohammadYounes/rtlcss#56]
Hi.
There is a problem with pointing basic labels in newer versions of Semantic-UI rtl build. Semantic UI version is 2.1.8.

```js
<div class="field">
    <label for="id_contact_name">نام</label>
    <input id="id_contact_name" maxlength="100" name="contact_name" type="text">
    <div class="ui pointing red basic label">این فیلد لازم است.</div>                    
</div>
```
![screenshot from 2016-02-22 09-02-25](https://cloud.githubusercontent.com/assets/2115303/13210297/09769ed8-d943-11e5-99f0-2bb90757db8c.png)

JSFiddle: https://jsfiddle.net/ty6j8ee5/

**Comment by MohammadYounes** [comment]
Hi,

This is not an issue with RTLCSS, You should report this issue at Semantic.

Thanks!
