### ISSUE TITLE
Stripping only changed property to new file

### ISSUE THREAD

**Issue by ariona** [MohammadYounes/rtlcss#59]
Is there any option for stripping newly changed props to new file. So the newly created css will output the changed property and selector not all the styles with different direction value.

**Comment by MohammadYounes** [comment]
No, As this tool is intended to provide complete automation. I recommend [creating a complete RTL version](https://github.com/MohammadYounes/rtlcss/wiki/Why-make-a-complete-RTL-version-%3F)

Thanks!

> Duplicate #13, #26, #30 and #34
