### ISSUE TITLE
About "tranform" rule support

### ISSUE THREAD

**Issue by MrPeak** [MohammadYounes/rtlcss#62]
Sometimes I want declare transform: scaleX(1) to make sure a element won't be scaled，so I expect `rtlcss` could replace `1` to `-1`. Then this element will flipX.

**Comment by MohammadYounes** [comment]
Changing it from 1 to -1 would break the text! How is this of value to the RTL version ?

**Comment by MrPeak** [comment]
Horizontal flip? That's `transform: scaleX(-1) `

**Comment by MohammadYounes** [comment]
Okay, what about the text ?
