### ISSUE TITLE
Adding an option to switch class names

### ISSUE THREAD

**Issue by salarmehr** [MohammadYounes/rtlcss#66]
# Consider this css file:

```
.float-right {
    float: right;
}
.float-left {
    float: left;
}
```

rtlcss converts that to:

```
.float-right {
    float: left;
}
.float-left {
    float: right;
}
```

As you can see now `.float-right` class make an item left floating. An option to update class names is really necessary.

**Comment by MohammadYounes** [comment]
How is this different from [`autoRename`](https://github.com/MohammadYounes/rtlcss#options-object)/[`stringMap`](https://github.com/MohammadYounes/rtlcss#stringmap-array) ?

**Comment by MohammadYounes** [comment]
Ah, these contain directional properties, so they wont be auto-renamed. But still you can use [`rename`](https://github.com/MohammadYounes/rtlcss#control-directives) directive ([example](https://tonicdev.com/mohammad/570f399dbb9b821200bf913d))

**Comment by MohammadYounes** [comment]
Closing, reason explained [here](https://github.com/Semantic-Org/Semantic-UI/issues/3922#issuecomment-209916992)

**Comment by salarmehr** [comment]
Using directives for that is cumbersome. Is it possible to add parameter to cmd to do that automatically?

**Comment by MohammadYounes** [comment]
What's the use case for this?  Why do you want the RTL version to be the same as the LTR one ?

**Comment by salarmehr** [comment]
When only RTL site is targeted and you want to use a css framework (e.g. Semantic, Mondenize, ...) you want to RTL that library and use it as if it was originally wrote in RTL mode.

**Comment by MohammadYounes** [comment]
Okay, I see. 

What you really want here is not an option to switch class names, but rather an option to ignore these rules. May be a setting based on a regex or a callback function of some sort!

**Comment by salarmehr** [comment]
@MohammadYounes  I am not sure you got that. What you mean by ignoring them? I mean the following conversion:

```
.float-right {
    float: right;
}
```
to

```
.float-left {
    float: left;
}
```

The source css file may only have `.float-right` class so you cannot ignore it.

**Comment by MohammadYounes** [comment]
So you want the effect of `/*rtl:rename*/` without having to set it explicitly ?

**Comment by salarmehr** [comment]
Yes, I do.
Sorry for late answer, I missed your question.

**Comment by nabileisa** [comment]
+1 for this feature as it would really be helpful in developing RTL-only sites using LTR only frameworks like Bootstrap

**Comment by MohammadYounes** [comment]
As of v2.2.0 you can use a [pre-hook](http://rtlcss.com/learn/usage-guide/hooks/) to wrap the input CSS inside a [rename directive](http://rtlcss.com/learn/usage-guide/control-directives/#rename):

```js
var hooks = {
  pre: function (css, postcss) {
    css.insertBefore(css.nodes[0], postcss.comment({text: 'rtl:begin:rename'}))
    css.insertAfter(css.nodes[css.nodes.length - 1], postcss.comment({text: 'rtl:end:rename'}))
  }
})
```

This will force renaming, and thus converting the following CSS:
```css
.float-right {
    float: right;
}
.float-left {
    float: left;
}
```

Into: 

```css
.float-left {
    float: left;
}
.float-right {
    float: right;
}
```

Thanks.
