### ISSUE TITLE
How to reverse the effect "LTR" ?

### ISSUE THREAD

**Issue by sidati** [MohammadYounes/rtlcss#67]
Salam Alaykum,
Can you please provide any code snippet or suggestion to reverse the effect : LTR instead of RTL ?
Ive lost my LTR files :)
Thanks in advance

**Comment by MohammadYounes** [comment]
Walaikum Assalam,

It's the same process, running on an RTL version would give you the LTR. ([example](https://tonicdev.com/mohammad/5714b5d79febf01100e76ea2))

**Comment by MohammadYounes** [comment]
Feel free to post here if you need further assistance with this.

**Comment by sidati** [comment]
Thank you very mush
