### ISSUE TITLE
problem with working RTLCSS in SASS file, about ignore commented code in sass

### ISSUE THREAD

**Issue by NabiKAZ** [MohammadYounes/rtlcss#69]
Thanks for great extension.
I have problem with working RTLCSS in SASS file.
When I use `/*rtl:append:{value}*/ ` and etc. and compile it, the sass ignore commented code, and then RTLCSS didn't see any commented code.

**Comment by MohammadYounes** [comment]
Use SASS [interpolation](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#interpolation_) syntax, passing your comment as string

```css
    body{ font-size: 14px #{"/*rtl:15px*/"}; }
```
will produce

```
    body { font-size: 14px /*rtl:15px*/; }
```

**Comment by dustin-page** [comment]
If you are using node-sass, Web Compiler or something similar to compile your CSS before using rtlcss you can use what's called "loud comments". The "!" is removed by the SASS compiler, but not the comment:

.icon-prev,
            .icon-next {
                z-index: 4;
                /*!rtl:raw:
                -moz-transform: scale(-1, 1);
                -webkit-transform: scale(-1, 1);
                -o-transform: scale(-1, 1);
                -ms-transform: scale(-1, 1);
                transform: scale(-1, 1);
                */
            }
