### ISSUE TITLE
flex box alignment problem (consider using the direction property).

### ISSUE THREAD

**Issue by tareif** [MohammadYounes/rtlcss#77]
I had a problem after I used the tool in this small component.

this is a popup component before using rtlcss .. hover over the box
http://codepen.io/anon/pen/kXvjLW

after using the tool:
http://codepen.io/anon/pen/wWpxJN

note that the flex container hasn't been affected, but if you changed the first css rule to this

```
* {
    box-sizing: border-box;
    direction: rtl;
}
```

the problem will be solved.

I'm not a css ninja but maybe if the tool inserts this css rule into the converted file may solve a lot of problems.

thanks a lot for the awesome tool.

**Comment by MohammadYounes** [comment]
Flexbox properties follow document direction. You have to either set the direction in your CSS or better on the document element `<html dir="rtl">` (http://codepen.io/anon/pen/JKrBvA).

Thanks!

> Dup. #28, #33

**Comment by MohammadYounes** [comment]
Also note that using the CSS approach does not require making all elements rtl, you just need to set it on the flex container, in your case: `html { direction: rtl }` (http://codepen.io/anon/pen/rLpkRd)
