### ISSUE TITLE
What features do you want to see in RTLCSS 3.0?

### ISSUE THREAD

**Issue by MohammadYounes** [MohammadYounes/rtlcss#78]
This is an open topic for discussing features you expect in v**3.0**

Your input is highly appreciated!

**Comment by salarmehr** [comment]
I build-in watcher would be  really useful to watch ltr version of files.
----------------
May you please also say the simplest  method to do that in the current version?

**Comment by MohammadYounes** [comment]
You may try this https://github.com/doowb/watch-cli

**Comment by salarmehr** [comment]
Thanks.  I have just tried `gulp-rtlcss` package in a gulp watch task. It seem it works seamlessly.

**Comment by ryanurban** [comment]
Hey @MohammadYounes, I just wanted to pop in and say thank you for this really awesome tool. It works very well and has been a pleasure to use on some of my projects. Also, fwiw, I just tried to give you a donation and PayPal is saying you can't accept funds right now or you need to setup your account or something.

Thanks again!

**Comment by MohammadYounes** [comment]
Thanks @ryanurban, I really appreciate it! 

Not sure what's wrong with PayPal, May be try to send it directly to the email mentioned in the donations page 😄

**Comment by ryanurban** [comment]
Is this the correct email: myounes@outlook.com?

**Comment by MohammadYounes** [comment]
Yup

**Comment by ryanurban** [comment]
Done, thanks again! If I think of anything for 3.0, I'll chime in here.

**Comment by MohammadYounes** [comment]
Sure thing! Very much appreciated.

**Comment by MohammadYounes** [comment]
@ryanurban Unfortunately, I didn't receive any donation till the moment! May be you need to re-check where did you send the payment!

> P.S: I sent you an email  (to: ryancurban@gmail.com ).

**Comment by smmoosavi** [comment]
copy fonts #89 
excluded .rtl.css files #90

**Comment by smmoosavi** [comment]
webpack plugin

**Comment by MohammadYounes** [comment]
@smmoosavi Thanks for the notes, as for the webpack plugin, currently there are:

* https://github.com/sidati/rtlcss-loader
* https://github.com/romainberger/rtl-css-loader
* https://github.com/romainberger/webpack-rtl-plugin

**Comment by smmoosavi** [comment]
load plugins via cli
```
rtlcss --plugin plugin1.js --plugin plugin2.js [...other options...]
```

**Comment by LeusMaximus** [comment]
Hi @MohammadYounes 
Thanks for rtlcss.
Is it possible to get result file with modified styles only? Not all styles?

**Comment by smmoosavi** [comment]
I think converting `style.css` to `style.common.css`, `style.rtl.css`, `style.ltr.css` is better.

**Comment by MohammadYounes** [comment]
@LeusMaximus I don't think I'll be adding such option.  This tool is intended to provide complete automation, it should generate a complete RTL style sheet. See [Why make a complete RTL version ?](https://github.com/MohammadYounes/rtlcss/wiki/Why-make-a-complete-RTL-version-%3F).

As for possibility, I think writing a postcss plugin to diff the two versions will be a much better approach.

@smmoosavi I might consider a bidi version similar to https://github.com/jakob101/postcss-inline-rtl

**Comment by Mustafa-Online** [comment]
محمد يونس، كل الود والتقدير على مجهودك الجباااار ^_^

**Comment by sajaddp** [comment]
A feature for remove non-override cods.
Sometimes we need find the changed codes for check them manually!

**Comment by MohammadYounes** [comment]
@sajaddp I don't fully understand your request. Would you clarify ?

**Comment by sajaddp** [comment]
@MohammadYounes 
RTL is not mirror anything and sometimes we need get modified styles in result for undo some wrong changes.
For example, changing 
`.text-left{
text-align:left;
}`
To 
`.text-left{
text-align:right;
}`
Is wrong.

**Comment by MohammadYounes** [comment]
@sajaddp For an LTR first approach, your example is not wrong. Anyhow, you can use a diff tool to locate the differences. Thanks.

**Comment by MohammadYounes** [comment]
@sajaddp Moreover, see the discussion over [here](https://github.com/MohammadYounes/rtlcss/issues/66).

**Comment by mehdiyatrib** [comment]
Thank you @MohammadYounes for the tool, it's very helpful
It's would be great if you can add the following option : 

Let's say I have the following code in my main css: 
body{
margin-left : 15px;
}

When applying the rtlcss you got : 
body{
margin-right: 15px;
}

It work good if you change the whole stylesheet, but in this case when add the code in a separate file you got this : 
body{
margin-left: 15px;
margin-right:15px;
}

Adding manually " margin-left:0 / inherit " will fix the prob, but it would be great if it was automated.

**Comment by MohammadYounes** [comment]
@mehdiyatrib adding `margin-left:0 / inherit` would fix the problem in some cases, not all of them - see [Why make a complete RTL version ?](https://github.com/MohammadYounes/rtlcss/wiki/Why-make-a-complete-RTL-version-%3F).

**Comment by sandrina-p** [comment]
Is it possible to output 2 files `index.css` and `index-rlt.css` ?

#### Input

`input.css`
```css
.foo {
  border: none;
  margin-right: 1rem;
  padding-left: 1rem; /*rtl:ignore*/
}
```
#### Output

`output.css`
```css
.foo {
  border: none;
  margin-right: 1rem;
  padding-left: 1rem;
}
```

`output-rtl.css`
```css
.foo {
  border: none;
  margin-left: 1rem;
  padding-left: 1rem;
}
```

This is better than having a file with everything:

`output.css`
```css
.foo {
  border: none;
  padding-left: 1rem;
}

[dir="ltr"] {
  margin-right: 1rem;
}

[dir="rtl"] {
  margin-left: 1rem;
}
```

**Comment by MohammadYounes** [comment]
@sandrina-p I think you are confusing this with another lib, as rtlcss only generates one output.

**Comment by sandrina-p** [comment]
Yh, you are right, working on that

**Comment by smmoosavi** [comment]
support for jss (css in js)

this is what [material-ui@next](https://material-ui-1dab0.firebaseapp.com/customization/css-in-js/) is using

https://github.com/cssinjs/jss/

**Comment by MohammadYounes** [comment]
Thanks @smmoosavi 

This is not a feature to add. It's a plugin that needs to be [authored](https://github.com/cssinjs/jss/blob/master/docs/plugins.md#authoring-plugins).

**Comment by KhaledSMQ** [comment]
@MohammedYouned
I think big impact can be done to separate RTL and LTR from original theme by generating 2 files
Means leave shared attributes in orginal file and generate 2 other files ``` theme.rtl.css and theme.ltr.css```  to make sure serving small footprint cascade files. One more convert render dome direct in the browser with needing to generate files for the theme

**Comment by MohammadYounes** [comment]
@KhaledSMQ Thank you! it will be considered.

**Comment by oscarhandsome** [comment]
i'm looking on the [example ](https://rtlcss.com/playground/#)
but when i try to add **/*rtl:prepend:"Droid Arabic Kufi",*/**
or **/*rtl:14px*/**
in my scss, in new css, i haven't this commands. i'm using your script, my own gulp, and  [gulp-rtlcss](https://github.com/jjlharrison/gulp-rtlcss)

anyway thanks for your's job!

**Comment by MohammadYounes** [comment]
@oscarhandsome All you need is to use SASS interpolation syntax as mentioned [here](https://rtlcss.com/learn/usage-guide/value-directives/#tip).

**Comment by oscarhandsome** [comment]
@MohammadYounes thank you for fast answer!
But this is didn't help me. [image](http://almall.elbargo.ru/interpolation.jpg)

How can i identify a problem?

**Comment by MohammadYounes** [comment]
@oscarhandsome May be you have it lost in minification? This is off the current topic, It would be better if you opened a separate issue.

**Comment by M6stafa** [comment]
@MohammadYounes, It is good that your postcss plugin has an option to generate rtl and ltr version of the input that separate with `dir attribute selector` or a class that comes from options too.
there is a [postcss plugin](https://www.npmjs.com/package/postcss-rtl) that do this now, but it has some issues.

**Comment by MohammadYounes** [comment]
@M6stafa It will be considered once I find time to work on v3 as mentioned [here](https://github.com/MohammadYounes/rtlcss/issues/78#issuecomment-284492078).

**Comment by LazZiya** [comment]
@MohammadYounes you did a great job, you saved me a lot of days :)

I tried the [online play ground](https://rtlcss.com/playground/) with [bootswatch themes](https://bootswatch.com/) but unfortunately couldn't produce a proper rtl versions of it. Is there any ready converted bootswatch themes? or shall we wait for the official versions?

**Comment by MohammadYounes** [comment]
Closing this as v3 is released with no major change, the main feature is compatibility with postcss 8.0
