### ISSUE TITLE
Problem with calc expression inside background-position

### ISSUE THREAD

**Issue by Termina1** [MohammadYounes/rtlcss#79]
Hi, there is a problem with calc.

```
background-position: calc(2px) 50%;
```

transforms to

```
background-position: calc(100%-(2px)) 50%;
```

which is not readable by browser (stable Chrome), this should be

```
background-position: calc(100% - (2px)) 50%;
```

**Comment by MohammadYounes** [comment]
Hi,

This is fixed in [2.0.5](https://github.com/MohammadYounes/rtlcss/blob/master/CHANGELOG.md#205---17-may-2016), Which version are you using ?

**Comment by Termina1** [comment]
@MohammadYounes I'm very sorry, I was using 2.0.2, updating the version helped. Thanks a lot!

**Comment by Termina1** [comment]
1
