### ISSUE TITLE
Problem with value directives

### ISSUE THREAD

**Issue by eleboys** [MohammadYounes/rtlcss#81]
Hello and special thanks for the great tool (rtlcss)

when you try to use this tool with some css transformers like sass/scss, they omit comments from css attributes so value directives will be useless in this case!
```css
body 
   color: red /*rtl:blue*/
```
=========== will convert to ========
```css
body {
   color: red;
}
```

**Comment by MohammadYounes** [comment]
Hello,

You need to use SASS interpolation syntax, see  #69

Thanks!

**Comment by masanzsa** [comment]
you could handle that with jQuery maybe? by injecting styling based on patterns? although this is a frontend solution and you may be looking for a backend one?
