### ISSUE TITLE
postcss tabs and playground spaces

### ISSUE THREAD

**Issue by mkstix6** [MohammadYounes/rtlcss#82]
I'm not attached to either tabs or spaces.
But.
When I use the rtlcss playground online I get spaces indentation.
When I use the postcss version I get tabs indentation.

Is there an option I can pass to the postcss version to get spaces indentation so they match up, please?

Thanks.

**Comment by MohammadYounes** [comment]
PostCSS detects indentation from your input, and the same goes for the playground, But if you use the  **Beautify**  option it will follow the provided **Settings** (default is 2 spaces).

![rtlcss-online-settings](https://cloud.githubusercontent.com/assets/4712046/18470508/830d3550-79b5-11e6-8e17-ca682fb9b431.png)


Thanks!

**Comment by mkstix6** [comment]
Got it. Thanks :)
