### ISSUE TITLE
Background shorthand with url first issue

### ISSUE THREAD

**Issue by PWRune** [MohammadYounes/rtlcss#84]
Hi Mohammad

I'm having trouble with the background shorthand syntax if the URL is put first, it doesn't seem to process it correctly. 
```
// broken:
background: url('/path/to/image.png') left top;
background: url('/path/to/image.png') left top / contain no-repeat;

// works: 
background: left top url('/path/to/image.png') ;
```
Tried on http://rtlcss.com/playground/ aswell same result.

**Comment by MohammadYounes** [comment]
@PWRune Thanks for reporting this, Seems all tests are made with position placed first 😕 

Will fix soon.
