### ISSUE TITLE
Support for CSS background-position edge offsets

### ISSUE THREAD

**Issue by marksticklingminttwist** [MohammadYounes/rtlcss#87]
http://caniuse.com/#feat=css-background-offsets

This original CSS:

`background-position: top 14px right 10px;`

...in my scenario, would ideally become...

`background-position: top 14px left 10px;`

**Comment by marksticklingminttwist** [comment]
Sorry, forgot to say please. Thanks.

**Comment by MohammadYounes** [comment]
To be added ... Thanks!

**Comment by mkstix6** [comment]
Thanks!
