### ISSUE TITLE
Every other ignore control directive within a block is ignored

### ISSUE THREAD

**Issue by yoavf** [MohammadYounes/rtlcss#88]
The following example is from the [docs](http://rtlcss.com/learn/usage-guide/control-directives/#ignore):
```
.code {
  /*rtl:ignore*/
  direction:ltr;
  /*rtl:ignore*/
  text-align:left;
}
```

The result when pasting this in the rtlcss playground:
```
.code {
  direction:ltr;
  /*rtl:ignore*/
  text-align:right;
}
```

Adding a 3rd line preceded with `/*rtl:ignore*/` works as expected. A 4th will have the same result as above, etc...

**Comment by MohammadYounes** [comment]
Fixed in 2.1.1
