### ISSUE TITLE
Support for CSS Clip Path 

### ISSUE THREAD

**Issue by oalansari82** [MohammadYounes/rtlcss#92]
I am using a clip-path property to draw shapes in CSS. Apparently, this isn't supported now. 

This is the original
`clip-path: polygon(90% 0%, 100% 50%, 90% 100%, 0% 100%, 10% 50%, 0% 0%);`

This is what it should be
`clip-path: polygon(100% 0%, 100% 50%, 100% 100%, 10% 100%, 0% 50%, 10% 0%);`

I understand that this is complex as it is drawing and in a lot of instances, the shapes will stay the same. However, it will be helpful to have this incorporated.

**Comment by oalansari82** [comment]
Having a second look at it, it can be implemented using `/*rtl:ignore*/`

However I am stuck trying to get it to work with SASS is this syntax correct `/*!rtl:ignore*/`

**Comment by MohammadYounes** [comment]
For such declarations, make use of rtlcss [value directives](http://rtlcss.com/learn/usage-guide/value-directives/). For example:

```css
clip-path: polygon(90% 0%, 100% 50%, 90% 100%, 0% 100%, 10% 50%, 0% 0%)/*rtl:polygon(100% 0%, 100% 50%, 100% 100%, 10% 100%, 0% 50%, 10% 0%)*/;
```

As for SASS, use interpolation syntax as described [here](https://github.com/MohammadYounes/rtlcss/issues/69#issuecomment-215682202).


```css
clip-path: polygon(90% 0%, 100% 50%, 90% 100%, 0% 100%, 10% 50%, 0% 0%) #{"/*rtl:polygon(100% 0%, 100% 50%, 100% 100%, 10% 100%, 0% 50%, 10% 0%)*/"};
```

Let me know if you need further assistance!
