### ISSUE TITLE
Exclude selectors

### ISSUE THREAD

**Issue by janschoenherr** [MohammadYounes/rtlcss#93]
Is it possible to exclude nodes that match a regex pattern? Similar to the _Ignore Control Directive_, but programmatically?

Or is it possible to do this with a plugin?

**Comment by MohammadYounes** [comment]
Yes, Plugins are the way to go. See this [example](https://github.com/MohammadYounes/rtlcss/issues/86#issuecomment-261875443).

**Comment by janschoenherr** [comment]
Thanks, that seems to be an example for variables though. I'd like to skip entire nodes, like:

```
/*rtl:ignore*/
.my-class {
  margin-left:5px;
}
```

**Comment by MohammadYounes** [comment]
In this case, you need to write a control directive as explained [here](http://rtlcss.com/learn/extending-rtlcss/control-directive-definition/) along with an [example](http://localhost:4000/learn/extending-rtlcss/control-directive-definition/#example)

**Comment by janschoenherr** [comment]
Thank you very much!

**Comment by janschoenherr** [comment]
Okay, just read through [the docs](http://rtlcss.com/learn/extending-rtlcss/writing-a-plugin/).

It seems that the directives are triggered through comments in the CSS only. I'd like to trigger them programmatically.

**Comment by MohammadYounes** [comment]
Not sure I understand, Would you describe the exact use case ?

**Comment by janschoenherr** [comment]
I have a css file e.g. with a class:
```
.margin-left {
  margin-left: 5px;
}
```
In this case I want the class _margin-left_ to explicitly set a left margin, in both the ltr and the rtl version. I'd rather not add the ```/*rtl:ignore*/``` comments to the CSS.

**Comment by MohammadYounes** [comment]
> I'd rather not add the /*rtl:ignore*/ comments to the CSS.

Why not use the directive ?

**Comment by MohammadYounes** [comment]
Is this related to #66 ?

**Comment by janschoenherr** [comment]
Well, it could be an external CSS file which I require into my project. 
Another reason would be, that if I later on decide to switch the rtl converter, it'd be much easier to do this by simply replacing the call to ```rtlcss.process()``` rather than going through all CSS files and swap the meta comments.

**Comment by janschoenherr** [comment]
Closing this as it seems to be a duplicate of #66.

**Comment by MohammadYounes** [comment]
If rtlcss provided you with some sort of hooks to manipulate the css before/after it is processed, would that solve your use-case ?

For example:
```js
config.hooks = { 
  pre: function (css) {
   ...
  }, 
  post: function (css) {
   ...
  }
}
```

**Comment by MohammadYounes** [comment]
@janschoenherr 

If you are up for a discussion join https://appear.in/rtlcss or https://gitter.im/MohammadYounes/rtlcss

**Comment by janschoenherr** [comment]
Thanks, the ```/*rtl:rename*/``` is working great.
