### ISSUE TITLE
LTR as default direction

### ISSUE THREAD

**Issue by Ziker22** [MohammadYounes/rtlcss#95]
Hi,
When dir is not defined in HTML tag  all bidir css properties are completely ignored resulting in page looking messy
Is there a chance you can add default direction either to options or as a fallback when nothing is specified ?

**Comment by MohammadYounes** [comment]
The recommendation is to add `dir="rtl"` to the html tag. See: 
* https://www.w3.org/International/questions/qa-html-dir
* https://www.w3.org/International/questions/qa-bidi-css-markup

**Comment by MohammadYounes** [comment]
Closing this and keeping the recommendation.
