### ISSUE TITLE
imporper operation

### ISSUE THREAD

**Issue by hauso** [MohammadYounes/rtlcss#98]
some parameters are not correctly converted
eg

```
div {
  margin: 0 10px 0 0;
}
```

should be converted to 
```
div {
  margin: 0 0 0 10px;
}
```

**Comment by MohammadYounes** [comment]
This is a very trivial conversion, It's hard to believe such error exists. Nevertheless, I ran it through rtlcss and the output was 100% correct. 

Try to check your setup.

Thanks!
