### ISSUE TITLE
[Documentation] Value Directives, when using SASS/SCSS

### ISSUE THREAD

**Issue by zaigham** [MohammadYounes/rtlcss#99]
Please add this note https://github.com/MohammadYounes/rtlcss/issues/69#issuecomment-215682202 here: http://rtlcss.com/learn/usage-guide/value-directives/#replace
Hopefully, next time it will save somebody's time. 😎

**Comment by MohammadYounes** [comment]
Added http://rtlcss.com/learn/usage-guide/value-directives/#tip

Thanks!
